/* packet-usb-ptp.h
 *
 * usb image picture transfer protocol dissector
 * (c)2013 Max Baker <max@warped.org>
 * (c)2022 Jake Merdich <jake@merdich.com>
 *
 * Much of this adapted from libgphoto2/libgphoto2/camlibs/ptp2/
 *
 * Copyright (C) 2001 Mariusz Woloszyn <emsi@ipartners.pl>
 * Copyright (C) 2003-2012 Marcus Meissner <marcus@jet.franken.de>
 * Copyright (C) 2006-2008 Linus Walleij <triad@df.lth.se>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#define IF_CLASS_IMAGE_SUBCLASS_PTP 0x01
#define IF_CLASS_IMAGE_PROTOCOL_PTP 0x01

/* 7.1.1 [1] */
#define USB_PTP_TYPE_CMD        0x1
#define USB_PTP_TYPE_DATA       0x2
#define USB_PTP_TYPE_RESPONSE   0x3
#define USB_PTP_TYPE_EVENT      0x4

#define USB_PTP_VENDOR_EXT_MTP 0x00000006

#define USB_PTP_VENDOR_CANON   0x04a9
#define USB_PTP_VENDOR_CASIO   0x07cf
#define USB_PTP_VENDOR_NIKON   0x04b0
#define USB_PTP_VENDOR_FUJI    0x04cb
#define USB_PTP_VENDOR_OLYMPUS 0x07b4
#define USB_PTP_VENDOR_KODAK   0x040a

#define USB_PTP_OC_GETDEVICEINFO           0x1001
#define USB_PTP_OC_GETSTORAGEIDS           0x1004
#define USB_PTP_OC_GETOBJECTHANDLES        0x1007
#define USB_PTP_OC_GETDEVICEPROPDESC       0x1014
#define USB_PTP_OC_SETDEVICEPROPVALUE      0x1016
#define USB_PTP_OC_GETOBJECTPROPSSUPPORTED 0x9801
#define USB_PTP_OC_GETOBJECTPROPDESC       0x9802

/* PTP device info structure (returned by GetDevInfo) */
typedef struct _usb_ptp_device_info_t {
    guint16       StandardVersion;
    guint32       VendorExtensionID;
    guint16       VendorExtensionVersion;
    gchar        *VendorExtensionDesc;
    guint16       FunctionalMode;
    value_string *OperationsSupported;
    value_string *EventsSupported;
    value_string *DevicePropertiesSupported;
    value_string *CaptureFormats;
    value_string *ImageFormats;
    gchar        *Manufacturer;
    gchar        *Model;
    gchar        *DeviceVersion;
    gchar        *SerialNumber;
} usb_ptp_device_info_t;

/* Struct stored into usb_conv that keeps track of decoded device information
 *      Gets attached to *class_data in usb_conv */
typedef struct _usb_ptp_conv_info_t {
    guint32                flavor;
    usb_ptp_device_info_t *device_info;
    /*usb_ptp_object_info_t *object_info; NOT Implemened yet*/
} usb_ptp_conv_info_t;

/* Mask Definition for Value Strings */
#define USB_PTP_FLAVOR_NONE      0x000
#define USB_PTP_FLAVOR_ALL       0x001
#define USB_PTP_FLAVOR_ANDROID   0x002
#define USB_PTP_FLAVOR_CANON     0x004
#define USB_PTP_FLAVOR_CASIO     0x008
#define USB_PTP_FLAVOR_KODAK     0x010
#define USB_PTP_FLAVOR_FUJI      0x020
#define USB_PTP_FLAVOR_MTP       0x040
#define USB_PTP_FLAVOR_NIKON     0x080
#define USB_PTP_FLAVOR_OLYMPUS   0x100

static const value_string usb_ptp_container_type_vals[] = {
    {USB_PTP_TYPE_CMD,      "Command Block"},
    {USB_PTP_TYPE_DATA,     "Data Block"},
    {USB_PTP_TYPE_RESPONSE, "Response Block"},
    {USB_PTP_TYPE_EVENT,    "Event Block"},
    {0, NULL}
};

/*
 *
 * SEMIAUTO-GENERATED CODE - The majority of these tables were auto-generated from tools/usb-ptp-extract-tables.pl
 *
 * NOTE: The tables contain additional information not in libgphoto, so you must hand merge the
 *       output from the above to these tables.
 *
 */

/* PTP_AC StorageInfo Access Capability */
static const value_string_masked_t usb_ptp_ac_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x0000, "ReadWrite"},
    {USB_PTP_FLAVOR_ALL       , 0x0001, "ReadOnly"},
    {USB_PTP_FLAVOR_ALL       , 0x0002, "ReadOnly_with_Object_Deletion"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_AT Association Types */
static const value_string_masked_t usb_ptp_at_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x0000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x0001, "GenericFolder"},
    {USB_PTP_FLAVOR_ALL       , 0x0002, "Album"},
    {USB_PTP_FLAVOR_ALL       , 0x0003, "TimeSequence"},
    {USB_PTP_FLAVOR_ALL       , 0x0004, "HorizontalPanoramic"},
    {USB_PTP_FLAVOR_ALL       , 0x0005, "VerticalPanoramic"},
    {USB_PTP_FLAVOR_ALL       , 0x0006, "2DPanoramic"},
    {USB_PTP_FLAVOR_ALL       , 0x0007, "AncillaryData"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_DPC Device Properties Codes */
static const value_string_masked_t usb_ptp_dpc_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x5000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x5001, "BatteryLevel"},
    {USB_PTP_FLAVOR_ALL       , 0x5002, "FunctionalMode"},
    {USB_PTP_FLAVOR_ALL       , 0x5003, "ImageSize"},
    {USB_PTP_FLAVOR_ALL       , 0x5004, "CompressionSetting"},
    {USB_PTP_FLAVOR_ALL       , 0x5005, "WhiteBalance"},
    {USB_PTP_FLAVOR_ALL       , 0x5006, "RGBGain"},
    {USB_PTP_FLAVOR_ALL       , 0x5007, "FNumber"},
    {USB_PTP_FLAVOR_ALL       , 0x5008, "FocalLength"},
    {USB_PTP_FLAVOR_ALL       , 0x5009, "FocusDistance"},
    {USB_PTP_FLAVOR_ALL       , 0x500a, "FocusMode"},
    {USB_PTP_FLAVOR_ALL       , 0x500b, "ExposureMeteringMode"},
    {USB_PTP_FLAVOR_ALL       , 0x500c, "FlashMode"},
    {USB_PTP_FLAVOR_ALL       , 0x500d, "ExposureTime"},
    {USB_PTP_FLAVOR_ALL       , 0x500e, "ExposureProgramMode"},
    {USB_PTP_FLAVOR_ALL       , 0x500f, "ExposureIndex"},
    {USB_PTP_FLAVOR_ALL       , 0x5010, "ExposureBiasCompensation"},
    {USB_PTP_FLAVOR_ALL       , 0x5011, "DateTime"},
    {USB_PTP_FLAVOR_ALL       , 0x5012, "CaptureDelay"},
    {USB_PTP_FLAVOR_ALL       , 0x5013, "StillCaptureMode"},
    {USB_PTP_FLAVOR_ALL       , 0x5014, "Contrast"},
    {USB_PTP_FLAVOR_ALL       , 0x5015, "Sharpness"},
    {USB_PTP_FLAVOR_ALL       , 0x5016, "DigitalZoom"},
    {USB_PTP_FLAVOR_ALL       , 0x5017, "EffectMode"},
    {USB_PTP_FLAVOR_ALL       , 0x5018, "BurstNumber"},
    {USB_PTP_FLAVOR_ALL       , 0x5019, "BurstInterval"},
    {USB_PTP_FLAVOR_ALL       , 0x501a, "TimelapseNumber"},
    {USB_PTP_FLAVOR_ALL       , 0x501b, "TimelapseInterval"},
    {USB_PTP_FLAVOR_ALL       , 0x501c, "FocusMeteringMode"},
    {USB_PTP_FLAVOR_ALL       , 0x501d, "UploadURL"},
    {USB_PTP_FLAVOR_ALL       , 0x501e, "Artist"},
    {USB_PTP_FLAVOR_ALL       , 0x501f, "CopyrightInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x5020, "SupportedStreams"},
    {USB_PTP_FLAVOR_ALL       , 0x5021, "EnabledStreams"},
    {USB_PTP_FLAVOR_ALL       , 0x5022, "VideoFormat"},
    {USB_PTP_FLAVOR_ALL       , 0x5023, "VideoResolution"},
    {USB_PTP_FLAVOR_ALL       , 0x5024, "VideoQuality"},
    {USB_PTP_FLAVOR_ALL       , 0x5025, "VideoFrameRate"},
    {USB_PTP_FLAVOR_ALL       , 0x5026, "VideoContrast"},
    {USB_PTP_FLAVOR_ALL       , 0x5027, "VideoBrightness"},
    {USB_PTP_FLAVOR_ALL       , 0x5028, "AudioFormat"},
    {USB_PTP_FLAVOR_ALL       , 0x5029, "AudioBitrate"},
    {USB_PTP_FLAVOR_ALL       , 0x502a, "AudioSamplingRate"},
    {USB_PTP_FLAVOR_ALL       , 0x502b, "AudioBitPerSample"},
    {USB_PTP_FLAVOR_ALL       , 0x502c, "AudioVolume"},
    {USB_PTP_FLAVOR_ALL       , 0xd000, "EXTENSION"},
    {USB_PTP_FLAVOR_KODAK     , 0xd001, "ColorTemperature"},
    {USB_PTP_FLAVOR_CASIO     , 0xd001, "MONITOR"},
    {USB_PTP_FLAVOR_CANON     , 0xd001, "BeepMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd002, "STORAGE"},
    {USB_PTP_FLAVOR_CANON     , 0xd002, "BatteryKind"},
    {USB_PTP_FLAVOR_KODAK     , 0xd002, "DateTimeStampFormat"},
    {USB_PTP_FLAVOR_CANON     , 0xd003, "BatteryStatus"},
    {USB_PTP_FLAVOR_KODAK     , 0xd003, "BeepMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd004, "UNKNOWN_1"},
    {USB_PTP_FLAVOR_KODAK     , 0xd004, "VideoOut"},
    {USB_PTP_FLAVOR_CANON     , 0xd004, "UILockType"},
    {USB_PTP_FLAVOR_CASIO     , 0xd005, "UNKNOWN_2"},
    {USB_PTP_FLAVOR_KODAK     , 0xd005, "PowerSaving"},
    {USB_PTP_FLAVOR_CANON     , 0xd005, "CameraMode"},
    {USB_PTP_FLAVOR_KODAK     , 0xd006, "UI_Language"},
    {USB_PTP_FLAVOR_CANON     , 0xd006, "ImageQuality"},
    {USB_PTP_FLAVOR_CANON     , 0xd007, "FullViewFileFormat"},
    {USB_PTP_FLAVOR_CASIO     , 0xd007, "UNKNOWN_3"},
    {USB_PTP_FLAVOR_CASIO     , 0xd008, "RECORD_LIGHT"},
    {USB_PTP_FLAVOR_CANON     , 0xd008, "ImageSize"},
    {USB_PTP_FLAVOR_CASIO     , 0xd009, "UNKNOWN_4"},
    {USB_PTP_FLAVOR_CANON     , 0xd009, "SelfTime"},
    {USB_PTP_FLAVOR_CANON     , 0xd00a, "FlashMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd00a, "UNKNOWN_5"},
    {USB_PTP_FLAVOR_CASIO     , 0xd00b, "MOVIE_MODE"},
    {USB_PTP_FLAVOR_CANON     , 0xd00b, "Beep"},
    {USB_PTP_FLAVOR_CANON     , 0xd00c, "ShootingMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd00c, "HD_SETTING"},
    {USB_PTP_FLAVOR_CASIO     , 0xd00d, "HS_SETTING"},
    {USB_PTP_FLAVOR_CANON     , 0xd00d, "ImageMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd00e, "DriveMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd00f, "CS_HIGH_SPEED"},
    {USB_PTP_FLAVOR_CANON     , 0xd00f, "EZoom"},
    {USB_PTP_FLAVOR_NIKON     , 0xd010, "ShootingBank"},
    {USB_PTP_FLAVOR_CANON     , 0xd010, "MeteringMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd010, "CS_UPPER_LIMIT"},
    {USB_PTP_FLAVOR_CANON     , 0xd011, "AFDistance"},
    {USB_PTP_FLAVOR_NIKON     , 0xd011, "ShootingBankNameA"},
    {USB_PTP_FLAVOR_CASIO     , 0xd011, "CS_SHOT"},
    {USB_PTP_FLAVOR_CASIO     , 0xd012, "UNKNOWN_6"},
    {USB_PTP_FLAVOR_CANON     , 0xd012, "FocusingPoint"},
    {USB_PTP_FLAVOR_NIKON     , 0xd012, "ShootingBankNameB"},
    {USB_PTP_FLAVOR_CANON     , 0xd013, "WhiteBalance"},
    {USB_PTP_FLAVOR_NIKON     , 0xd013, "ShootingBankNameC"},
    {USB_PTP_FLAVOR_CASIO     , 0xd013, "UNKNOWN_7"},
    {USB_PTP_FLAVOR_CANON     , 0xd014, "SlowShutterSetting"},
    {USB_PTP_FLAVOR_NIKON     , 0xd014, "ShootingBankNameD"},
    {USB_PTP_FLAVOR_CASIO     , 0xd015, "UNKNOWN_8"},
    {USB_PTP_FLAVOR_CANON     , 0xd015, "AFMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd015, "ResetBank0"},
    {USB_PTP_FLAVOR_NIKON     , 0xd016, "RawCompression"},
    {USB_PTP_FLAVOR_CANON     , 0xd016, "ImageStabilization"},
    {USB_PTP_FLAVOR_FUJI      , 0xd017, "ColorTemperature"},
    {USB_PTP_FLAVOR_CASIO     , 0xd017, "UNKNOWN_9"},
    {USB_PTP_FLAVOR_NIKON     , 0xd017, "WhiteBalanceAutoBias"},
    {USB_PTP_FLAVOR_CANON     , 0xd017, "Contrast"},
    {USB_PTP_FLAVOR_FUJI      , 0xd018, "Quality"},
    {USB_PTP_FLAVOR_CANON     , 0xd018, "ColorGain"},
    {USB_PTP_FLAVOR_NIKON     , 0xd018, "WhiteBalanceTungstenBias"},
    {USB_PTP_FLAVOR_CASIO     , 0xd018, "UNKNOWN_10"},
    {USB_PTP_FLAVOR_CASIO     , 0xd019, "UNKNOWN_11"},
    {USB_PTP_FLAVOR_CANON     , 0xd019, "Sharpness"},
    {USB_PTP_FLAVOR_NIKON     , 0xd019, "WhiteBalanceFluorescentBias"},
    {USB_PTP_FLAVOR_CANON     , 0xd01a, "Sensitivity"},
    {USB_PTP_FLAVOR_NIKON     , 0xd01a, "WhiteBalanceDaylightBias"},
    {USB_PTP_FLAVOR_CASIO     , 0xd01a, "UNKNOWN_12"},
    {USB_PTP_FLAVOR_CASIO     , 0xd01b, "UNKNOWN_13"},
    {USB_PTP_FLAVOR_CANON     , 0xd01b, "ParameterSet"},
    {USB_PTP_FLAVOR_NIKON     , 0xd01b, "WhiteBalanceFlashBias"},
    {USB_PTP_FLAVOR_NIKON     , 0xd01c, "WhiteBalanceCloudyBias"},
    {USB_PTP_FLAVOR_CANON     , 0xd01c, "ISOSpeed"},
    {USB_PTP_FLAVOR_CASIO     , 0xd01c, "UNKNOWN_14"},
    {USB_PTP_FLAVOR_NIKON     , 0xd01d, "WhiteBalanceShadeBias"},
    {USB_PTP_FLAVOR_CANON     , 0xd01d, "Aperture"},
    {USB_PTP_FLAVOR_CASIO     , 0xd01d, "UNKNOWN_15"},
    {USB_PTP_FLAVOR_CANON     , 0xd01e, "ShutterSpeed"},
    {USB_PTP_FLAVOR_NIKON     , 0xd01e, "WhiteBalanceColorTemperature"},
    {USB_PTP_FLAVOR_CANON     , 0xd01f, "ExpCompensation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd01f, "WhiteBalancePresetNo"},
    {USB_PTP_FLAVOR_CANON     , 0xd020, "FlashCompensation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd020, "WhiteBalancePresetName0"},
    {USB_PTP_FLAVOR_CASIO     , 0xd020, "UNKNOWN_16"},
    {USB_PTP_FLAVOR_NIKON     , 0xd021, "WhiteBalancePresetName1"},
    {USB_PTP_FLAVOR_CANON     , 0xd021, "AEBExposureCompensation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd022, "WhiteBalancePresetName2"},
    {USB_PTP_FLAVOR_CANON     , 0xd023, "AvOpen"},
    {USB_PTP_FLAVOR_NIKON     , 0xd023, "WhiteBalancePresetName3"},
    {USB_PTP_FLAVOR_CANON     , 0xd024, "AvMax"},
    {USB_PTP_FLAVOR_NIKON     , 0xd024, "WhiteBalancePresetName4"},
    {USB_PTP_FLAVOR_NIKON     , 0xd025, "WhiteBalancePresetVal0"},
    {USB_PTP_FLAVOR_CANON     , 0xd025, "FocalLength"},
    {USB_PTP_FLAVOR_CANON     , 0xd026, "FocalLengthTele"},
    {USB_PTP_FLAVOR_NIKON     , 0xd026, "WhiteBalancePresetVal1"},
    {USB_PTP_FLAVOR_NIKON     , 0xd027, "WhiteBalancePresetVal2"},
    {USB_PTP_FLAVOR_CANON     , 0xd027, "FocalLengthWide"},
    {USB_PTP_FLAVOR_NIKON     , 0xd028, "WhiteBalancePresetVal3"},
    {USB_PTP_FLAVOR_CANON     , 0xd028, "FocalLengthDenominator"},
    {USB_PTP_FLAVOR_CANON     , 0xd029, "CaptureTransferMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd029, "WhiteBalancePresetVal4"},
    {USB_PTP_FLAVOR_CANON     , 0xd02a, "Zoom"},
    {USB_PTP_FLAVOR_NIKON     , 0xd02a, "ImageSharpening"},
    {USB_PTP_FLAVOR_NIKON     , 0xd02b, "ToneCompensation"},
    {USB_PTP_FLAVOR_CANON     , 0xd02b, "NamePrefix"},
    {USB_PTP_FLAVOR_NIKON     , 0xd02c, "ColorModel"},
    {USB_PTP_FLAVOR_CANON     , 0xd02c, "SizeQualityMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd02d, "SupportedThumbSize"},
    {USB_PTP_FLAVOR_NIKON     , 0xd02d, "HueAdjustment"},
    {USB_PTP_FLAVOR_CANON     , 0xd02e, "SizeOfOutputDataFromCamera"},
    {USB_PTP_FLAVOR_NIKON     , 0xd02e, "NonCPULensDataFocalLength"},
    {USB_PTP_FLAVOR_NIKON     , 0xd02f, "NonCPULensDataMaximumAperture"},
    {USB_PTP_FLAVOR_CANON     , 0xd02f, "SizeOfInputDataToCamera"},
    {USB_PTP_FLAVOR_CANON     , 0xd030, "RemoteAPIVersion"},
    {USB_PTP_FLAVOR_CASIO     , 0xd030, "UNKNOWN_17"},
    {USB_PTP_FLAVOR_NIKON     , 0xd030, "ShootingMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd031, "JPEG_Compression_Policy"},
    {USB_PTP_FLAVOR_CANON     , 0xd031, "FirmwareVersion"},
    {USB_PTP_FLAVOR_CANON     , 0xd032, "CameraModel"},
    {USB_PTP_FLAVOR_NIKON     , 0xd032, "ColorSpace"},
    {USB_PTP_FLAVOR_CANON     , 0xd033, "CameraOwner"},
    {USB_PTP_FLAVOR_NIKON     , 0xd033, "AutoDXCrop"},
    {USB_PTP_FLAVOR_NIKON     , 0xd034, "FlickerReduction"},
    {USB_PTP_FLAVOR_CANON     , 0xd034, "UnixTime"},
    {USB_PTP_FLAVOR_CANON     , 0xd035, "CameraBodyID"},
    {USB_PTP_FLAVOR_NIKON     , 0xd035, "RemoteMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd036, "CameraOutput"},
    {USB_PTP_FLAVOR_NIKON     , 0xd036, "VideoMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd037, "EffectMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd037, "DispAv"},
    {USB_PTP_FLAVOR_CANON     , 0xd038, "AvOpenApex"},
    {USB_PTP_FLAVOR_CANON     , 0xd039, "DZoomMagnification"},
    {USB_PTP_FLAVOR_CANON     , 0xd03a, "MlSpotPos"},
    {USB_PTP_FLAVOR_CANON     , 0xd03b, "DispAvMax"},
    {USB_PTP_FLAVOR_CANON     , 0xd03c, "AvMaxApex"},
    {USB_PTP_FLAVOR_CANON     , 0xd03d, "EZoomStartPosition"},
    {USB_PTP_FLAVOR_CANON     , 0xd03e, "FocalLengthOfTele"},
    {USB_PTP_FLAVOR_CANON     , 0xd03f, "EZoomSizeOfTele"},
    {USB_PTP_FLAVOR_CANON     , 0xd040, "PhotoEffect"},
    {USB_PTP_FLAVOR_NIKON     , 0xd040, "CSMMenuBankSelect"},
    {USB_PTP_FLAVOR_NIKON     , 0xd041, "MenuBankNameA"},
    {USB_PTP_FLAVOR_CANON     , 0xd041, "AssistLight"},
    {USB_PTP_FLAVOR_CANON     , 0xd042, "FlashQuantityCount"},
    {USB_PTP_FLAVOR_NIKON     , 0xd042, "MenuBankNameB"},
    {USB_PTP_FLAVOR_CANON     , 0xd043, "RotationAngle"},
    {USB_PTP_FLAVOR_NIKON     , 0xd043, "MenuBankNameC"},
    {USB_PTP_FLAVOR_CANON     , 0xd044, "RotationScene"},
    {USB_PTP_FLAVOR_NIKON     , 0xd044, "MenuBankNameD"},
    {USB_PTP_FLAVOR_CANON     , 0xd045, "EventEmulateMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd045, "ResetBank"},
    {USB_PTP_FLAVOR_CANON     , 0xd046, "DPOFVersion"},
    {USB_PTP_FLAVOR_CANON     , 0xd047, "TypeOfSupportedSlideShow"},
    {USB_PTP_FLAVOR_NIKON     , 0xd048, "A1AFCModePriority"},
    {USB_PTP_FLAVOR_CANON     , 0xd048, "AverageFilesizes"},
    {USB_PTP_FLAVOR_NIKON     , 0xd049, "A2AFSModePriority"},
    {USB_PTP_FLAVOR_CANON     , 0xd049, "ModelID"},
    {USB_PTP_FLAVOR_NIKON     , 0xd04a, "A3GroupDynamicAF"},
    {USB_PTP_FLAVOR_NIKON     , 0xd04b, "A4AFActivation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd04c, "FocusAreaIllumManualFocus"},
    {USB_PTP_FLAVOR_NIKON     , 0xd04d, "FocusAreaIllumContinuous"},
    {USB_PTP_FLAVOR_NIKON     , 0xd04e, "FocusAreaIllumWhenSelected"},
    {USB_PTP_FLAVOR_NIKON     , 0xd04f, "FocusAreaWrap"},
    {USB_PTP_FLAVOR_NIKON     , 0xd050, "VerticalAFON"},
    {USB_PTP_FLAVOR_NIKON     , 0xd051, "AFLockOn"},
    {USB_PTP_FLAVOR_NIKON     , 0xd052, "FocusAreaZone"},
    {USB_PTP_FLAVOR_NIKON     , 0xd053, "EnableCopyright"},
    {USB_PTP_FLAVOR_NIKON     , 0xd054, "ISOAuto"},
    {USB_PTP_FLAVOR_NIKON     , 0xd055, "EVISOStep"},
    {USB_PTP_FLAVOR_NIKON     , 0xd056, "EVStep"},
    {USB_PTP_FLAVOR_NIKON     , 0xd057, "EVStepExposureComp"},
    {USB_PTP_FLAVOR_NIKON     , 0xd058, "ExposureCompensation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd059, "CenterWeightArea"},
    {USB_PTP_FLAVOR_NIKON     , 0xd05a, "ExposureBaseMatrix"},
    {USB_PTP_FLAVOR_NIKON     , 0xd05b, "ExposureBaseCenter"},
    {USB_PTP_FLAVOR_NIKON     , 0xd05c, "ExposureBaseSpot"},
    {USB_PTP_FLAVOR_NIKON     , 0xd05d, "LiveViewAFArea"},
    {USB_PTP_FLAVOR_NIKON     , 0xd05e, "AELockMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd05f, "AELAFLMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd061, "LiveViewAFFocus"},
    {USB_PTP_FLAVOR_NIKON     , 0xd062, "MeterOff"},
    {USB_PTP_FLAVOR_NIKON     , 0xd063, "SelfTimer"},
    {USB_PTP_FLAVOR_NIKON     , 0xd064, "MonitorOff"},
    {USB_PTP_FLAVOR_NIKON     , 0xd065, "ImgConfTime"},
    {USB_PTP_FLAVOR_NIKON     , 0xd066, "AutoOffTimers"},
    {USB_PTP_FLAVOR_NIKON     , 0xd067, "AngleLevel"},
    {USB_PTP_FLAVOR_NIKON     , 0xd068, "D1ShootingSpeed"},
    {USB_PTP_FLAVOR_NIKON     , 0xd069, "D2MaximumShots"},
    {USB_PTP_FLAVOR_NIKON     , 0xd06a, "ExposureDelayMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd06b, "LongExposureNoiseReduction"},
    {USB_PTP_FLAVOR_NIKON     , 0xd06c, "FileNumberSequence"},
    {USB_PTP_FLAVOR_NIKON     , 0xd06d, "ControlPanelFinderRearControl"},
    {USB_PTP_FLAVOR_NIKON     , 0xd06e, "ControlPanelFinderViewfinder"},
    {USB_PTP_FLAVOR_NIKON     , 0xd06f, "D7Illumination"},
    {USB_PTP_FLAVOR_NIKON     , 0xd070, "NrHighISO"},
    {USB_PTP_FLAVOR_NIKON     , 0xd071, "SHSET_CH_GUID_DISP"},
    {USB_PTP_FLAVOR_NIKON     , 0xd072, "ArtistName"},
    {USB_PTP_FLAVOR_NIKON     , 0xd073, "CopyrightInfo"},
    {USB_PTP_FLAVOR_NIKON     , 0xd074, "FlashSyncSpeed"},
    {USB_PTP_FLAVOR_NIKON     , 0xd075, "FlashShutterSpeed"},
    {USB_PTP_FLAVOR_NIKON     , 0xd076, "E3AAFlashMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd077, "E4ModelingFlash"},
    {USB_PTP_FLAVOR_NIKON     , 0xd078, "BracketSet"},
    {USB_PTP_FLAVOR_NIKON     , 0xd079, "E6ManualModeBracketing"},
    {USB_PTP_FLAVOR_NIKON     , 0xd07a, "BracketOrder"},
    {USB_PTP_FLAVOR_NIKON     , 0xd07b, "E8AutoBracketSelection"},
    {USB_PTP_FLAVOR_NIKON     , 0xd07c, "BracketingSet"},
    {USB_PTP_FLAVOR_NIKON     , 0xd080, "F1CenterButtonShootingMode"},
    {USB_PTP_FLAVOR_CASIO     , 0xd080, "UNKNOWN_18"},
    {USB_PTP_FLAVOR_NIKON     , 0xd081, "CenterButtonPlaybackMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd082, "F2Multiselector"},
    {USB_PTP_FLAVOR_NIKON     , 0xd083, "F3PhotoInfoPlayback"},
    {USB_PTP_FLAVOR_NIKON     , 0xd084, "F4AssignFuncButton"},
    {USB_PTP_FLAVOR_NIKON     , 0xd085, "F5CustomizeCommDials"},
    {USB_PTP_FLAVOR_NIKON     , 0xd086, "ReverseCommandDial"},
    {USB_PTP_FLAVOR_NIKON     , 0xd087, "ApertureSetting"},
    {USB_PTP_FLAVOR_NIKON     , 0xd088, "MenusAndPlayback"},
    {USB_PTP_FLAVOR_NIKON     , 0xd089, "F6ButtonsAndDials"},
    {USB_PTP_FLAVOR_NIKON     , 0xd08a, "NoCFCard"},
    {USB_PTP_FLAVOR_NIKON     , 0xd08b, "CenterButtonZoomRatio"},
    {USB_PTP_FLAVOR_NIKON     , 0xd08c, "FunctionButton2"},
    {USB_PTP_FLAVOR_NIKON     , 0xd08d, "AFAreaPoint"},
    {USB_PTP_FLAVOR_NIKON     , 0xd08e, "NormalAFOn"},
    {USB_PTP_FLAVOR_NIKON     , 0xd08f, "CleanImageSensor"},
    {USB_PTP_FLAVOR_NIKON     , 0xd090, "ImageCommentString"},
    {USB_PTP_FLAVOR_NIKON     , 0xd091, "ImageCommentEnable"},
    {USB_PTP_FLAVOR_NIKON     , 0xd092, "ImageRotation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd093, "ManualSetLensNo"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0a0, "MovScreenSize"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0a1, "MovVoice"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0a2, "MovMicrophone"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0a3, "MovFileSlot"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0a6, "ManualMovieSetting"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0b3, "MonitorOffDelay"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0c0, "Bracketing"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0c1, "AutoExposureBracketStep"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0c2, "AutoExposureBracketProgram"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0c3, "AutoExposureBracketCount"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0c4, "WhiteBalanceBracketStep"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0c5, "WhiteBalanceBracketProgram"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e0, "LensID"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e1, "LensSort"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e2, "LensType"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e3, "FocalLengthMin"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e4, "FocalLengthMax"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e5, "MaxApAtMinFocalLength"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0e6, "MaxApAtMaxFocalLength"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f0, "FinderISODisp"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f2, "AutoOffPhoto"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f3, "AutoOffMenu"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f4, "AutoOffInfo"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f5, "SelfTimerShootNum"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f7, "VignetteCtrl"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f8, "AutoDistortionControl"},
    {USB_PTP_FLAVOR_NIKON     , 0xd0f9, "SceneMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd100, "ExposureTime"},
    {USB_PTP_FLAVOR_MTP       , 0xd101, "SecureTime"},
    {USB_PTP_FLAVOR_NIKON     , 0xd101, "ACPower"},
    {USB_PTP_FLAVOR_CANON     , 0xd101, "Aperture"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd102, "ResolutionMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd102, "ShutterSpeed"},
    {USB_PTP_FLAVOR_NIKON     , 0xd102, "WarningStatus"},
    {USB_PTP_FLAVOR_MTP       , 0xd102, "DeviceCertificate"},
    {USB_PTP_FLAVOR_NIKON     , 0xd103, "MaximumShots"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd103, "FocusPriority"},
    {USB_PTP_FLAVOR_MTP       , 0xd103, "RevocationInfo"},
    {USB_PTP_FLAVOR_CANON     , 0xd103, "ISOSpeed"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd104, "DriveMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd104, "AFLockStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd104, "ExpCompensation"},
    {USB_PTP_FLAVOR_CANON     , 0xd105, "AutoExposureMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd105, "AELockStatus"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd105, "DateTimeFormat"},
    {USB_PTP_FLAVOR_CANON     , 0xd106, "DriveMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd106, "ExposureBiasStep"},
    {USB_PTP_FLAVOR_NIKON     , 0xd106, "FVLockStatus"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd107, "WBMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd107, "AutofocusLCDTopMode2"},
    {USB_PTP_FLAVOR_CANON     , 0xd107, "MeteringMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd108, "AutofocusArea"},
    {USB_PTP_FLAVOR_CANON     , 0xd108, "FocusMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd108, "OneTouchWB"},
    {USB_PTP_FLAVOR_CANON     , 0xd109, "WhiteBalance"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd109, "ManualWB"},
    {USB_PTP_FLAVOR_NIKON     , 0xd109, "FlexibleProgram"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd10a, "ManualWBRBBias"},
    {USB_PTP_FLAVOR_NIKON     , 0xd10a, "LightMeter"},
    {USB_PTP_FLAVOR_CANON     , 0xd10a, "ColorTemperature"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd10b, "CustomWB"},
    {USB_PTP_FLAVOR_CANON     , 0xd10b, "WhiteBalanceAdjustA"},
    {USB_PTP_FLAVOR_NIKON     , 0xd10b, "RecordingMedia"},
    {USB_PTP_FLAVOR_CANON     , 0xd10c, "WhiteBalanceAdjustB"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd10c, "CustomWBValue"},
    {USB_PTP_FLAVOR_NIKON     , 0xd10c, "USBSpeed"},
    {USB_PTP_FLAVOR_CANON     , 0xd10d, "WhiteBalanceXA"},
    {USB_PTP_FLAVOR_NIKON     , 0xd10d, "CCDNumber"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd10d, "ExposureTimeEx"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd10e, "BulbMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd10e, "WhiteBalanceXB"},
    {USB_PTP_FLAVOR_NIKON     , 0xd10e, "CameraOrientation"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd10f, "AntiMirrorMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd10f, "ColorSpace"},
    {USB_PTP_FLAVOR_NIKON     , 0xd10f, "GroupPtnType"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd110, "AEBracketingFrame"},
    {USB_PTP_FLAVOR_NIKON     , 0xd110, "FNumberLock"},
    {USB_PTP_FLAVOR_CANON     , 0xd110, "PictureStyle"},
    {USB_PTP_FLAVOR_CANON     , 0xd111, "BatteryPower"},
    {USB_PTP_FLAVOR_NIKON     , 0xd111, "ExposureApertureLock"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd111, "AEBracketingStep"},
    {USB_PTP_FLAVOR_CANON     , 0xd112, "BatterySelect"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd112, "WBBracketingFrame"},
    {USB_PTP_FLAVOR_NIKON     , 0xd112, "TVLockSetting"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd112, "WBBracketingRBFrame"},
    {USB_PTP_FLAVOR_NIKON     , 0xd113, "AVLockSetting"},
    {USB_PTP_FLAVOR_CANON     , 0xd113, "CameraTime"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd113, "WBBracketingRBRange"},
    {USB_PTP_FLAVOR_NIKON     , 0xd114, "IllumSetting"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd114, "WBBracketingGMFrame"},
    {USB_PTP_FLAVOR_NIKON     , 0xd115, "FocusPointBright"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd115, "WBBracketingGMRange"},
    {USB_PTP_FLAVOR_CANON     , 0xd115, "Owner"},
    {USB_PTP_FLAVOR_CANON     , 0xd116, "ModelID"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd118, "FLBracketingFrame"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd119, "FLBracketingStep"},
    {USB_PTP_FLAVOR_CANON     , 0xd119, "PTPExtensionVersion"},
    {USB_PTP_FLAVOR_CANON     , 0xd11a, "DPOFVersion"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd11a, "FlashBiasCompensation"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd11b, "ManualFocusMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd11b, "AvailableShots"},
    {USB_PTP_FLAVOR_CANON     , 0xd11c, "CaptureDestination"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd11d, "RawSaveMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd11d, "BracketMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd11e, "CurrentStorage"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd11e, "AUXLightMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd11f, "LensSinkMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd11f, "CurrentFolder"},
    {USB_PTP_FLAVOR_NIKON     , 0xd120, "ExternalFlashAttached"},
    {USB_PTP_FLAVOR_CANON     , 0xd120, "ImageFormat"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd120, "BeepStatus"},
    {USB_PTP_FLAVOR_NIKON     , 0xd121, "ExternalFlashStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd121, "ImageFormatCF"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd122, "ColorSpace"},
    {USB_PTP_FLAVOR_CANON     , 0xd122, "ImageFormatSD"},
    {USB_PTP_FLAVOR_NIKON     , 0xd122, "ExternalFlashSort"},
    {USB_PTP_FLAVOR_CANON     , 0xd123, "ImageFormatExtHD"},
    {USB_PTP_FLAVOR_NIKON     , 0xd123, "ExternalFlashMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd123, "ColorMatching"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd124, "Saturation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd124, "ExternalFlashCompensation"},
    {USB_PTP_FLAVOR_NIKON     , 0xd125, "NewExternalFlashMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd126, "NoiseReductionPattern"},
    {USB_PTP_FLAVOR_NIKON     , 0xd126, "FlashExposureCompensation"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd127, "NoiseReductionRandom"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd129, "ShadingMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd12a, "ISOBoostMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd12b, "ExposureIndexBiasStep"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd12c, "FilterEffect"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd12d, "ColorTune"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd12e, "Language"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd12f, "LanguageCode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd130, "HDRMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd130, "RecviewMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd130, "CompressionS"},
    {USB_PTP_FLAVOR_NIKON     , 0xd131, "HDRHighDynamic"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd131, "SleepTime"},
    {USB_PTP_FLAVOR_MTP       , 0xd131, "PlaysForSureID"},
    {USB_PTP_FLAVOR_CANON     , 0xd131, "CompressionM1"},
    {USB_PTP_FLAVOR_NIKON     , 0xd132, "HDRSmoothing"},
    {USB_PTP_FLAVOR_MTP       , 0xd132, "ZUNE_UNKNOWN2"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd132, "ManualWBGMBias"},
    {USB_PTP_FLAVOR_CANON     , 0xd132, "CompressionM2"},
    {USB_PTP_FLAVOR_CANON     , 0xd133, "CompressionL"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd135, "AELAFLMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd136, "AELButtonStatus"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd137, "CompressionSettingEx"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd139, "ToneMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd13a, "GradationMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd13b, "DevelopMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd13c, "ExtendInnerFlashMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd13d, "OutputDeviceMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd13e, "LiveViewMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd140, "OptimizeImage"},
    {USB_PTP_FLAVOR_CANON     , 0xd140, "PCWhiteBalance1"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd140, "LCDBacklight"},
    {USB_PTP_FLAVOR_CANON     , 0xd141, "PCWhiteBalance2"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd141, "CustomDevelop"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd142, "GradationAutoBias"},
    {USB_PTP_FLAVOR_NIKON     , 0xd142, "Saturation"},
    {USB_PTP_FLAVOR_CANON     , 0xd142, "PCWhiteBalance3"},
    {USB_PTP_FLAVOR_CANON     , 0xd143, "PCWhiteBalance4"},
    {USB_PTP_FLAVOR_NIKON     , 0xd143, "BW_FillerEffect"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd143, "FlashRCMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd144, "BW_Sharpness"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd144, "FlashRCGroupValue"},
    {USB_PTP_FLAVOR_CANON     , 0xd144, "PCWhiteBalance5"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd145, "FlashRCChannelValue"},
    {USB_PTP_FLAVOR_NIKON     , 0xd145, "BW_Contrast"},
    {USB_PTP_FLAVOR_CANON     , 0xd145, "MWhiteBalance"},
    {USB_PTP_FLAVOR_NIKON     , 0xd146, "BW_Setting_Type"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd146, "FlashRCFPMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd147, "FlashRCPhotoChromicMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd148, "FlashRCPhotoChromicBias"},
    {USB_PTP_FLAVOR_NIKON     , 0xd148, "Slot2SaveMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd149, "RawBitMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd149, "FlashRCPhotoChromicManualBias"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd14a, "FlashRCQuantityLightLevel"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd14b, "FocusMeteringValue"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd14c, "ISOBracketingFrame"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd14d, "ISOBracketingStep"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd14e, "BulbMFMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd14e, "ISOAutoTime"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd14f, "BurstFPSValue"},
    {USB_PTP_FLAVOR_NIKON     , 0xd14f, "FlourescentType"},
    {USB_PTP_FLAVOR_NIKON     , 0xd150, "TuneColourTemperature"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd150, "ISOAutoBaseValue"},
    {USB_PTP_FLAVOR_CANON     , 0xd150, "PictureStyleStandard"},
    {USB_PTP_FLAVOR_CANON     , 0xd151, "PictureStylePortrait"},
    {USB_PTP_FLAVOR_NIKON     , 0xd151, "TunePreset0"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd151, "ISOAutoMaxValue"},
    {USB_PTP_FLAVOR_NIKON     , 0xd152, "TunePreset1"},
    {USB_PTP_FLAVOR_CANON     , 0xd152, "PictureStyleLandscape"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd152, "BulbLimiterValue"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd153, "DPIMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd153, "PictureStyleNeutral"},
    {USB_PTP_FLAVOR_NIKON     , 0xd153, "TunePreset2"},
    {USB_PTP_FLAVOR_CANON     , 0xd154, "PictureStyleFaithful"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd154, "DPICustomValue"},
    {USB_PTP_FLAVOR_NIKON     , 0xd154, "TunePreset3"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd155, "ResolutionValueSetting"},
    {USB_PTP_FLAVOR_CANON     , 0xd155, "PictureStyleBlackWhite"},
    {USB_PTP_FLAVOR_NIKON     , 0xd155, "TunePreset4"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd157, "AFTargetSize"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd158, "LightSensorMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd159, "AEBracket"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd15a, "WBRBBracket"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd15b, "WBGMBracket"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd15c, "FlashBracket"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd15d, "ISOBracket"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xd15e, "MyModeStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd160, "PictureStyleUserSet1"},
    {USB_PTP_FLAVOR_NIKON     , 0xd160, "BeepOff"},
    {USB_PTP_FLAVOR_CANON     , 0xd161, "PictureStyleUserSet2"},
    {USB_PTP_FLAVOR_NIKON     , 0xd161, "AutofocusMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd162, "PictureStyleUserSet3"},
    {USB_PTP_FLAVOR_NIKON     , 0xd163, "AFAssist"},
    {USB_PTP_FLAVOR_NIKON     , 0xd164, "PADVPMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd165, "ImageReview"},
    {USB_PTP_FLAVOR_NIKON     , 0xd166, "AFAreaIllumination"},
    {USB_PTP_FLAVOR_NIKON     , 0xd167, "FlashMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd168, "FlashCommanderMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd169, "FlashSign"},
    {USB_PTP_FLAVOR_NIKON     , 0xd16a, "ISO_Auto"},
    {USB_PTP_FLAVOR_NIKON     , 0xd16b, "RemoteTimeout"},
    {USB_PTP_FLAVOR_NIKON     , 0xd16c, "GridDisplay"},
    {USB_PTP_FLAVOR_NIKON     , 0xd16d, "FlashModeManualPower"},
    {USB_PTP_FLAVOR_NIKON     , 0xd16e, "FlashModeCommanderPower"},
    {USB_PTP_FLAVOR_NIKON     , 0xd16f, "AutoFP"},
    {USB_PTP_FLAVOR_CANON     , 0xd170, "PictureStyleParam1"},
    {USB_PTP_FLAVOR_CANON     , 0xd171, "PictureStyleParam2"},
    {USB_PTP_FLAVOR_CANON     , 0xd172, "PictureStyleParam3"},
    {USB_PTP_FLAVOR_CANON     , 0xd17f, "FlavorLUTParams"},
    {USB_PTP_FLAVOR_NIKON     , 0xd180, "CSMMenu"},
    {USB_PTP_FLAVOR_CANON     , 0xd180, "CustomFunc1"},
    {USB_PTP_FLAVOR_MTP       , 0xd181, "ZUNE_UNKNOWN1"},
    {USB_PTP_FLAVOR_MTP       , 0xd181, "Zune_UnknownVersion"},
    {USB_PTP_FLAVOR_CANON     , 0xd181, "CustomFunc2"},
    {USB_PTP_FLAVOR_NIKON     , 0xd181, "WarningDisplay"},
    {USB_PTP_FLAVOR_CANON     , 0xd182, "CustomFunc3"},
    {USB_PTP_FLAVOR_NIKON     , 0xd182, "BatteryCellKind"},
    {USB_PTP_FLAVOR_CANON     , 0xd183, "CustomFunc4"},
    {USB_PTP_FLAVOR_NIKON     , 0xd183, "ISOAutoHiLimit"},
    {USB_PTP_FLAVOR_NIKON     , 0xd184, "DynamicAFArea"},
    {USB_PTP_FLAVOR_CANON     , 0xd184, "CustomFunc5"},
    {USB_PTP_FLAVOR_CANON     , 0xd185, "CustomFunc6"},
    {USB_PTP_FLAVOR_CANON     , 0xd186, "CustomFunc7"},
    {USB_PTP_FLAVOR_NIKON     , 0xd186, "ContinuousSpeedHigh"},
    {USB_PTP_FLAVOR_NIKON     , 0xd187, "InfoDispSetting"},
    {USB_PTP_FLAVOR_CANON     , 0xd187, "CustomFunc8"},
    {USB_PTP_FLAVOR_CANON     , 0xd188, "CustomFunc9"},
    {USB_PTP_FLAVOR_NIKON     , 0xd189, "PreviewButton"},
    {USB_PTP_FLAVOR_CANON     , 0xd189, "CustomFunc10"},
    {USB_PTP_FLAVOR_CANON     , 0xd18a, "CustomFunc11"},
    {USB_PTP_FLAVOR_NIKON     , 0xd18a, "PreviewButton2"},
    {USB_PTP_FLAVOR_CANON     , 0xd18b, "CustomFunc12"},
    {USB_PTP_FLAVOR_NIKON     , 0xd18b, "AEAFLockButton2"},
    {USB_PTP_FLAVOR_CANON     , 0xd18c, "CustomFunc13"},
    {USB_PTP_FLAVOR_NIKON     , 0xd18d, "IndicatorDisp"},
    {USB_PTP_FLAVOR_CANON     , 0xd18d, "CustomFunc14"},
    {USB_PTP_FLAVOR_CANON     , 0xd18e, "CustomFunc15"},
    {USB_PTP_FLAVOR_NIKON     , 0xd18e, "CellKindPriority"},
    {USB_PTP_FLAVOR_CANON     , 0xd18f, "CustomFunc16"},
    {USB_PTP_FLAVOR_NIKON     , 0xd190, "BracketingFramesAndSteps"},
    {USB_PTP_FLAVOR_CANON     , 0xd190, "CustomFunc17"},
    {USB_PTP_FLAVOR_CANON     , 0xd191, "CustomFunc18"},
    {USB_PTP_FLAVOR_CANON     , 0xd192, "CustomFunc19"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1a0, "LiveViewMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a0, "CustomFuncEx"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1a1, "LiveViewDriveMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a1, "MyMenu"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a2, "MyMenuList"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1a2, "LiveViewStatus"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1a3, "LiveViewImageZoomRatio"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a3, "WftStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a4, "WftInputTransmission"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1a4, "LiveViewProhibitCondition"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a5, "HDDirectoryStructure"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a6, "BatteryInfo"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a7, "AdapterInfo"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a8, "LensStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1a9, "QuickReviewTime"},
    {USB_PTP_FLAVOR_CANON     , 0xd1aa, "CardExtension"},
    {USB_PTP_FLAVOR_CANON     , 0xd1ab, "TempStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1ac, "ShutterCounter"},
    {USB_PTP_FLAVOR_CANON     , 0xd1ad, "SpecialOption"},
    {USB_PTP_FLAVOR_CANON     , 0xd1ae, "PhotoStudioMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd1af, "SerialNumber"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1b0, "ExposureDisplayStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b0, "EVFOutputDevice"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1b1, "ExposureIndicateStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b1, "EVFMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1b2, "InfoDispErrStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b2, "DepthOfFieldPreview"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1b3, "ExposureIndicateLightup"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b3, "EVFSharpness"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b4, "EVFWBMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b5, "EVFClickWBCoeffs"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b6, "EVFColorTemp"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b7, "ExposureSimMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd1b8, "EVFRecordStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xd1ba, "LvAfSystem"},
    {USB_PTP_FLAVOR_CANON     , 0xd1bb, "MovSize"},
    {USB_PTP_FLAVOR_CANON     , 0xd1bc, "LvViewTypeSelect"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1c0, "FlashOpen"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1c1, "FlashCharged"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d0, "FlashMRepeatValue"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d0, "Artist"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d1, "FlashMRepeatCount"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d1, "Copyright"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d2, "BracketValue"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d2, "FlashMRepeatInterval"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d3, "FocusInfoEx"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d3, "FlashCommandChannel"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d4, "DepthOfField"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d4, "FlashCommandSelfMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d5, "FlashCommandSelfCompensation"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d5, "Brightness"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d6, "FlashCommandSelfValue"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d6, "LensAdjustParams"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d7, "EFComp"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d7, "FlashCommandAMode"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d8, "FlashCommandACompensation"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d8, "LensName"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1d9, "FlashCommandAValue"},
    {USB_PTP_FLAVOR_CANON     , 0xd1d9, "AEB"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1da, "FlashCommandBMode"},
    {USB_PTP_FLAVOR_CANON     , 0xd1da, "StroboSetting"},
    {USB_PTP_FLAVOR_CANON     , 0xd1db, "StroboWirelessSetting"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1db, "FlashCommandBCompensation"},
    {USB_PTP_FLAVOR_CANON     , 0xd1dc, "StroboFiring"},
    {USB_PTP_FLAVOR_NIKON     , 0xd1dc, "FlashCommandBValue"},
    {USB_PTP_FLAVOR_CANON     , 0xd1dd, "LensID"},
    {USB_PTP_FLAVOR_NIKON     , 0xd200, "ActivePicCtrlItem"},
    {USB_PTP_FLAVOR_NIKON     , 0xd201, "ChangePicCtrlItem"},
    {USB_PTP_FLAVOR_FUJI      , 0xd201, "ReleaseMode"},
    {USB_PTP_FLAVOR_FUJI      , 0xd206, "FocusAreas"},
    {USB_PTP_FLAVOR_FUJI      , 0xd213, "AELock"},
    {USB_PTP_FLAVOR_MTP       , 0xd215, "ZUNE_UNKNOWN3"},
    {USB_PTP_FLAVOR_MTP       , 0xd216, "ZUNE_UNKNOWN4"},
    {USB_PTP_FLAVOR_FUJI      , 0xd218, "Aperture"},
    {USB_PTP_FLAVOR_FUJI      , 0xd219, "ShutterSpeed"},
    {USB_PTP_FLAVOR_MTP       , 0xd401, "SynchronizationPartner"},
    {USB_PTP_FLAVOR_MTP       , 0xd402, "DeviceFriendlyName"},
    {USB_PTP_FLAVOR_MTP       , 0xd403, "VolumeLevel"},
    {USB_PTP_FLAVOR_MTP       , 0xd405, "DeviceIcon"},
    {USB_PTP_FLAVOR_MTP       , 0xd406, "SessionInitiatorInfo"},
    {USB_PTP_FLAVOR_MTP       , 0xd407, "PerceivedDeviceType"},
    {USB_PTP_FLAVOR_MTP       , 0xd410, "PlaybackRate"},
    {USB_PTP_FLAVOR_MTP       , 0xd411, "PlaybackObject"},
    {USB_PTP_FLAVOR_MTP       , 0xd412, "PlaybackContainerIndex"},
    {USB_PTP_FLAVOR_MTP       , 0xd413, "PlaybackPosition"},
    {USB_PTP_FLAVOR_ALL       , 0xf000, "EXTENSION_MASK"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_DPFF Device Property Form Flag */
static const value_string_masked_t usb_ptp_dpff_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x00, "None"},
    {USB_PTP_FLAVOR_ALL       , 0x01, "Range"},
    {USB_PTP_FLAVOR_ALL       , 0x02, "Enumeration"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_DPGS Device Property GetSet type */
static const value_string_masked_t usb_ptp_dpgs_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x00, "Get"},
    {USB_PTP_FLAVOR_ALL       , 0x01, "GetSet"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_DTC Data Type Codes */
static const value_string_masked_t usb_ptp_dtc_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x0000, "UNDEF"},
    {USB_PTP_FLAVOR_ALL       , 0x0001, "INT8"},
    {USB_PTP_FLAVOR_ALL       , 0x0002, "UINT8"},
    {USB_PTP_FLAVOR_ALL       , 0x0003, "INT16"},
    {USB_PTP_FLAVOR_ALL       , 0x0004, "UINT16"},
    {USB_PTP_FLAVOR_ALL       , 0x0005, "INT32"},
    {USB_PTP_FLAVOR_ALL       , 0x0006, "UINT32"},
    {USB_PTP_FLAVOR_ALL       , 0x0007, "INT64"},
    {USB_PTP_FLAVOR_ALL       , 0x0008, "UINT64"},
    {USB_PTP_FLAVOR_ALL       , 0x0009, "INT128"},
    {USB_PTP_FLAVOR_ALL       , 0x000a, "UINT128"},
    {USB_PTP_FLAVOR_ALL       , 0x4001, "AINT8"},
    {USB_PTP_FLAVOR_ALL       , 0x4002, "AUINT8"},
    {USB_PTP_FLAVOR_ALL       , 0x4003, "AINT16"},
    {USB_PTP_FLAVOR_ALL       , 0x4004, "AUINT16"},
    {USB_PTP_FLAVOR_ALL       , 0x4005, "AINT32"},
    {USB_PTP_FLAVOR_ALL       , 0x4006, "AUINT32"},
    {USB_PTP_FLAVOR_ALL       , 0x4007, "AINT64"},
    {USB_PTP_FLAVOR_ALL       , 0x4008, "AUINT64"},
    {USB_PTP_FLAVOR_ALL       , 0x4009, "AINT128"},
    {USB_PTP_FLAVOR_ALL       , 0x400a, "AUINT128"},
    {USB_PTP_FLAVOR_ALL       , 0xffff, "STR"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_EC Event Codes */
static const value_string_masked_t usb_ptp_ec_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x4000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x4001, "CancelTransaction"},
    {USB_PTP_FLAVOR_ALL       , 0x4002, "ObjectAdded"},
    {USB_PTP_FLAVOR_ALL       , 0x4003, "ObjectRemoved"},
    {USB_PTP_FLAVOR_ALL       , 0x4004, "StoreAdded"},
    {USB_PTP_FLAVOR_ALL       , 0x4005, "StoreRemoved"},
    {USB_PTP_FLAVOR_ALL       , 0x4006, "DevicePropChanged"},
    {USB_PTP_FLAVOR_ALL       , 0x4007, "ObjectInfoChanged"},
    {USB_PTP_FLAVOR_ALL       , 0x4008, "DeviceInfoChanged"},
    {USB_PTP_FLAVOR_ALL       , 0x4009, "RequestObjectTransfer"},
    {USB_PTP_FLAVOR_ALL       , 0x400a, "StoreFull"},
    {USB_PTP_FLAVOR_ALL       , 0x400b, "DeviceReset"},
    {USB_PTP_FLAVOR_ALL       , 0x400c, "StorageInfoChanged"},
    {USB_PTP_FLAVOR_ALL       , 0x400d, "CaptureComplete"},
    {USB_PTP_FLAVOR_ALL       , 0x400e, "UnreportedStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xc005, "ExtendedErrorcode"},
    {USB_PTP_FLAVOR_CANON     , 0xc008, "ObjectInfoChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc009, "RequestObjectTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0xc00b, "ShutterButtonPressed0"},
    {USB_PTP_FLAVOR_CANON     , 0xc00c, "CameraModeChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc00e, "ShutterButtonPressed1"},
    {USB_PTP_FLAVOR_CANON     , 0xc011, "StartDirectTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0xc013, "StopDirectTransfer"},
    {USB_PTP_FLAVOR_NIKON     , 0xc101, "ObjectAddedInSDRAM"},
    {USB_PTP_FLAVOR_CANON     , 0xc101, "RequestGetEvent"},
    {USB_PTP_FLAVOR_NIKON     , 0xc102, "CaptureCompleteRecInSdram"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xc102, "PropertyChanged"},
    {USB_PTP_FLAVOR_NIKON     , 0xc103, "AdvancedTransfer"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0xc103, "CaptureComplete"},
    {USB_PTP_FLAVOR_NIKON     , 0xc104, "PreviewImageAdded"},
    {USB_PTP_FLAVOR_CANON     , 0xc181, "ObjectAddedEx"},
    {USB_PTP_FLAVOR_CANON     , 0xc182, "ObjectRemoved"},
    {USB_PTP_FLAVOR_CANON     , 0xc183, "RequestGetObjectInfoEx"},
    {USB_PTP_FLAVOR_CANON     , 0xc184, "StorageStatusChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc185, "StorageInfoChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc186, "RequestObjectTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0xc187, "ObjectInfoChangedEx"},
    {USB_PTP_FLAVOR_CANON     , 0xc188, "ObjectContentChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc189, "PropValueChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc18a, "AvailListChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc18b, "CameraStatusChanged"},
    {USB_PTP_FLAVOR_CANON     , 0xc18d, "WillSoonShutdown"},
    {USB_PTP_FLAVOR_CANON     , 0xc18e, "ShutdownTimerUpdated"},
    {USB_PTP_FLAVOR_CANON     , 0xc18f, "RequestCancelTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0xc190, "RequestObjectTransferDT"},
    {USB_PTP_FLAVOR_CANON     , 0xc191, "RequestCancelTransferDT"},
    {USB_PTP_FLAVOR_CANON     , 0xc192, "StoreAdded"},
    {USB_PTP_FLAVOR_CANON     , 0xc193, "StoreRemoved"},
    {USB_PTP_FLAVOR_CANON     , 0xc194, "BulbExposureTime"},
    {USB_PTP_FLAVOR_CANON     , 0xc195, "RecordingTime"},
    {USB_PTP_FLAVOR_CANON     , 0xc1a2, "RequestObjectTransferTS"},
    {USB_PTP_FLAVOR_CANON     , 0xc1a3, "AfResult"},
    {USB_PTP_FLAVOR_MTP       , 0xc801, "ObjectPropChanged"},
    {USB_PTP_FLAVOR_MTP       , 0xc802, "ObjectPropDescChanged"},
    {USB_PTP_FLAVOR_MTP       , 0xc803, "ObjectReferencesChanged"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};

/* PTP_VENDOR Vendor IDs */
static const value_string usb_ptp_devinfo_vendorextensionid_vals[] = {
    {0x00000001,"EASTMAN_KODAK"},
    {0x00000002,"SEIKO_EPSON"},
    {0x00000003,"AGILENT"},
    {0x00000004,"POLAROID"},
    {0x00000005,"AGFA_GEVAERT"},
    {0x00000006,"MTP"}, /* MICROSOFT */
    {0x00000007,"EQUINOX"},
    {0x00000008,"VIEWQUEST"},
    {0x00000009,"STMICROELECTRONICS"},
    {0x0000000A,"NIKON"},
    {0x0000000B,"CANON"},
    {0x0000000C,"FOTONATION"},
    {0x0000000D,"PENTAX"},
    {0x0000000E,"FUJI"},
    {0xffffffff,"MTP"},
    {0x00000000, NULL}
};

/* PTP_FST FilesystemType Values */
static const value_string_masked_t usb_ptp_fst_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x0000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x0001, "GenericFlat"},
    {USB_PTP_FLAVOR_ALL       , 0x0002, "GenericHierarchical"},
    {USB_PTP_FLAVOR_ALL       , 0x0003, "DCF"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_GOH GetObjectHandles */
static const value_string_masked_t usb_ptp_goh_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x00000000, "ALL_ASSOCS"},
    {USB_PTP_FLAVOR_ALL       , 0x00000000, "ALL_FORMATS"},
    {USB_PTP_FLAVOR_ALL       , 0xffffffff, "ROOT_PARENT"},
    {USB_PTP_FLAVOR_ALL       , 0xffffffff, "ALL_STORAGE"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_OC Operation Codes */
static const value_string_masked_t usb_ptp_oc_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x1000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x1001, "GetDeviceInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x1002, "OpenSession"},
    {USB_PTP_FLAVOR_ALL       , 0x1004, "GetStorageIDs"},
    {USB_PTP_FLAVOR_ALL       , 0x1005, "GetStorageInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x1006, "GetNumObjects"},
    {USB_PTP_FLAVOR_ALL       , 0x1007, "GetObjectHandles"},
    {USB_PTP_FLAVOR_ALL       , 0x1008, "GetObjectInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x1009, "GetObject"},
    {USB_PTP_FLAVOR_ALL       , 0x100a, "GetThumb"},
    {USB_PTP_FLAVOR_ALL       , 0x100b, "DeleteObject"},
    {USB_PTP_FLAVOR_ALL       , 0x100c, "SendObjectInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x100d, "SendObject"},
    {USB_PTP_FLAVOR_ALL       , 0x100e, "InitiateCapture"},
    {USB_PTP_FLAVOR_ALL       , 0x100f, "FormatStore"},
    {USB_PTP_FLAVOR_ALL       , 0x1010, "ResetDevice"},
    {USB_PTP_FLAVOR_ALL       , 0x1011, "SelfTest"},
    {USB_PTP_FLAVOR_ALL       , 0x1012, "SetObjectProtection"},
    {USB_PTP_FLAVOR_ALL       , 0x1013, "PowerDown"},
    {USB_PTP_FLAVOR_ALL       , 0x1014, "GetDevicePropDesc"},
    {USB_PTP_FLAVOR_ALL       , 0x1015, "GetDevicePropValue"},
    {USB_PTP_FLAVOR_ALL       , 0x1016, "SetDevicePropValue"},
    {USB_PTP_FLAVOR_ALL       , 0x1017, "ResetDevicePropValue"},
    {USB_PTP_FLAVOR_ALL       , 0x1018, "TerminateOpenCapture"},
    {USB_PTP_FLAVOR_ALL       , 0x1019, "MoveObject"},
    {USB_PTP_FLAVOR_ALL       , 0x101a, "CopyObject"},
    {USB_PTP_FLAVOR_ALL       , 0x101b, "GetPartialObject"},
    {USB_PTP_FLAVOR_ALL       , 0x101c, "InitiateOpenCapture"},
    {USB_PTP_FLAVOR_ALL       , 0x101d, "StartEnumHandles"},
    {USB_PTP_FLAVOR_ALL       , 0x101e, "EnumHandles"},
    {USB_PTP_FLAVOR_ALL       , 0x101f, "StopEnumHandles"},
    {USB_PTP_FLAVOR_ALL       , 0x1020, "GetVendorExtensionMaps"},
    {USB_PTP_FLAVOR_ALL       , 0x1021, "GetVendorDeviceInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x1022, "GetResizedImageObject"},
    {USB_PTP_FLAVOR_ALL       , 0x1023, "GetFilesystemManifest"},
    {USB_PTP_FLAVOR_ALL       , 0x1024, "GetStreamInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x1025, "GetStream"},
    {USB_PTP_FLAVOR_ALL       , 0x9000, "EXTENSION"},
    {USB_PTP_FLAVOR_CASIO     , 0x9001, "STILL_START"},
    {USB_PTP_FLAVOR_CANON     , 0x9001, "GetPartialObjectInfo"},
    {USB_PTP_FLAVOR_CASIO     , 0x9002, "STILL_STOP"},
    {USB_PTP_FLAVOR_CANON     , 0x9002, "SetObjectArchive"},
    {USB_PTP_FLAVOR_KODAK     , 0x9003, "GetSerial"},
    {USB_PTP_FLAVOR_CANON     , 0x9003, "KeepDeviceOn"},
    {USB_PTP_FLAVOR_KODAK     , 0x9004, "SetSerial"},
    {USB_PTP_FLAVOR_CANON     , 0x9004, "LockDeviceUI"},
    {USB_PTP_FLAVOR_CANON     , 0x9005, "UnlockDeviceUI"},
    {USB_PTP_FLAVOR_KODAK     , 0x9005, "SendFileObjectInfo"},
    {USB_PTP_FLAVOR_KODAK     , 0x9006, "SendFileObject"},
    {USB_PTP_FLAVOR_NIKON     , 0x9006, "GetProfileAllData"},
    {USB_PTP_FLAVOR_CANON     , 0x9006, "GetObjectHandleByName"},
    {USB_PTP_FLAVOR_CASIO     , 0x9007, "FOCUS"},
    {USB_PTP_FLAVOR_NIKON     , 0x9007, "SendProfileData"},
    {USB_PTP_FLAVOR_KODAK     , 0x9008, "SetText"},
    {USB_PTP_FLAVOR_CANON     , 0x9008, "InitiateReleaseControl"},
    {USB_PTP_FLAVOR_NIKON     , 0x9008, "DeleteProfile"},
    {USB_PTP_FLAVOR_NIKON     , 0x9009, "SetProfileData"},
    {USB_PTP_FLAVOR_CASIO     , 0x9009, "CF_PRESS"},
    {USB_PTP_FLAVOR_CANON     , 0x9009, "TerminateReleaseControl"},
    {USB_PTP_FLAVOR_CASIO     , 0x900a, "CF_RELEASE"},
    {USB_PTP_FLAVOR_CANON     , 0x900a, "TerminatePlaybackMode"},
    {USB_PTP_FLAVOR_CANON     , 0x900b, "ViewfinderOn"},
    {USB_PTP_FLAVOR_CANON     , 0x900c, "ViewfinderOff"},
    {USB_PTP_FLAVOR_CASIO     , 0x900c, "GET_OBJECT_INFO"},
    {USB_PTP_FLAVOR_CANON     , 0x900d, "DoAeAfAwb"},
    {USB_PTP_FLAVOR_CANON     , 0x900e, "GetCustomizeSpec"},
    {USB_PTP_FLAVOR_CANON     , 0x900f, "GetCustomizeItemInfo"},
    {USB_PTP_FLAVOR_NIKON     , 0x9010, "AdvancedTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0x9010, "GetCustomizeData"},
    {USB_PTP_FLAVOR_CANON     , 0x9011, "SetCustomizeData"},
    {USB_PTP_FLAVOR_NIKON     , 0x9011, "GetFileInfoInBlock"},
    {USB_PTP_FLAVOR_CANON     , 0x9012, "GetCaptureStatus"},
    {USB_PTP_FLAVOR_CANON     , 0x9013, "CheckEvent"},
    {USB_PTP_FLAVOR_CANON     , 0x9014, "FocusLock"},
    {USB_PTP_FLAVOR_CANON     , 0x9015, "FocusUnlock"},
    {USB_PTP_FLAVOR_CANON     , 0x9016, "GetLocalReleaseParam"},
    {USB_PTP_FLAVOR_CANON     , 0x9017, "SetLocalReleaseParam"},
    {USB_PTP_FLAVOR_CANON     , 0x9018, "AskAboutPcEvf"},
    {USB_PTP_FLAVOR_CANON     , 0x9019, "SendPartialObject"},
    {USB_PTP_FLAVOR_CANON     , 0x901a, "InitiateCaptureInMemory"},
    {USB_PTP_FLAVOR_CANON     , 0x901b, "GetPartialObjectEx"},
    {USB_PTP_FLAVOR_CANON     , 0x901c, "SetObjectTime"},
    {USB_PTP_FLAVOR_CANON     , 0x901d, "GetViewfinderImage"},
    {USB_PTP_FLAVOR_CANON     , 0x901e, "GetObjectAttributes"},
    {USB_PTP_FLAVOR_CANON     , 0x901f, "ChangeUSBProtocol"},
    {USB_PTP_FLAVOR_CANON     , 0x9020, "GetChanges"},
    {USB_PTP_FLAVOR_CANON     , 0x9021, "GetObjectInfoEx"},
    {USB_PTP_FLAVOR_CANON     , 0x9022, "InitiateDirectTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0x9023, "TerminateDirectTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0x9024, "SendObjectInfoByPath"},
    {USB_PTP_FLAVOR_CASIO     , 0x9024, "SHUTTER"},
    {USB_PTP_FLAVOR_CASIO     , 0x9025, "GET_OBJECT"},
    {USB_PTP_FLAVOR_CANON     , 0x9025, "SendObjectByPath"},
    {USB_PTP_FLAVOR_CANON     , 0x9026, "InitiateDirectTansferEx"},
    {USB_PTP_FLAVOR_CASIO     , 0x9026, "GET_THUMBNAIL"},
    {USB_PTP_FLAVOR_CANON     , 0x9027, "GetAncillaryObjectHandles"},
    {USB_PTP_FLAVOR_CASIO     , 0x9027, "GET_STILL_HANDLES"},
    {USB_PTP_FLAVOR_CASIO     , 0x9028, "STILL_RESET"},
    {USB_PTP_FLAVOR_CANON     , 0x9028, "GetTreeInfo"},
    {USB_PTP_FLAVOR_CASIO     , 0x9029, "HALF_PRESS"},
    {USB_PTP_FLAVOR_CANON     , 0x9029, "GetTreeSize"},
    {USB_PTP_FLAVOR_CASIO     , 0x902a, "HALF_RELEASE"},
    {USB_PTP_FLAVOR_CANON     , 0x902a, "NotifyProgress"},
    {USB_PTP_FLAVOR_CASIO     , 0x902b, "CS_PRESS"},
    {USB_PTP_FLAVOR_CANON     , 0x902b, "NotifyCancelAccepted"},
    {USB_PTP_FLAVOR_CASIO     , 0x902c, "CS_RELEASE"},
    {USB_PTP_FLAVOR_CANON     , 0x902c, "902C"},
    {USB_PTP_FLAVOR_CANON     , 0x902d, "GetDirectory"},
    {USB_PTP_FLAVOR_CASIO     , 0x902d, "ZOOM"},
    {USB_PTP_FLAVOR_CASIO     , 0x902e, "CZ_PRESS"},
    {USB_PTP_FLAVOR_CASIO     , 0x902f, "CZ_RELEASE"},
    {USB_PTP_FLAVOR_CANON     , 0x9030, "SetPairingInfo"},
    {USB_PTP_FLAVOR_CANON     , 0x9031, "GetPairingInfo"},
    {USB_PTP_FLAVOR_CANON     , 0x9032, "DeletePairingInfo"},
    {USB_PTP_FLAVOR_CANON     , 0x9033, "GetMACAddress"},
    {USB_PTP_FLAVOR_CANON     , 0x9034, "SetDisplayMonitor"},
    {USB_PTP_FLAVOR_CANON     , 0x9035, "PairingComplete"},
    {USB_PTP_FLAVOR_CANON     , 0x9036, "GetWirelessMAXChannel"},
    {USB_PTP_FLAVOR_CASIO     , 0x9041, "MOVIE_START"},
    {USB_PTP_FLAVOR_CASIO     , 0x9042, "MOVIE_STOP"},
    {USB_PTP_FLAVOR_CASIO     , 0x9043, "MOVIE_PRESS"},
    {USB_PTP_FLAVOR_CASIO     , 0x9044, "MOVIE_RELEASE"},
    {USB_PTP_FLAVOR_CASIO     , 0x9045, "GET_MOVIE_HANDLES"},
    {USB_PTP_FLAVOR_CASIO     , 0x9046, "MOVIE_RESET"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c0, "Capture"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c1, "AfDrive"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c2, "SetControlMode"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c3, "DelImageSDRAM"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c4, "GetLargeThumb"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c5, "CurveDownload"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c6, "CurveUpload"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c7, "CheckEvent"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c8, "DeviceReady"},
    {USB_PTP_FLAVOR_NIKON     , 0x90c9, "SetPreWBData"},
    {USB_PTP_FLAVOR_NIKON     , 0x90ca, "GetVendorPropCodes"},
    {USB_PTP_FLAVOR_NIKON     , 0x90cb, "AfCaptureSDRAM"},
    {USB_PTP_FLAVOR_NIKON     , 0x90cc, "GetPictCtrlData"},
    {USB_PTP_FLAVOR_NIKON     , 0x90cd, "SetPictCtrlData"},
    {USB_PTP_FLAVOR_NIKON     , 0x90ce, "DelCstPicCtrl"},
    {USB_PTP_FLAVOR_NIKON     , 0x90cf, "GetPicCtrlCapability"},
    {USB_PTP_FLAVOR_NIKON     , 0x90e0, "GetDevicePTPIPInfo"},
    {USB_PTP_FLAVOR_CANON     , 0x9101, "GetStorageIDs"},
    {USB_PTP_FLAVOR_MTP       , 0x9101, "WMDRMPD_GetSecureTimeChallenge"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9101, "Capture"},
    {USB_PTP_FLAVOR_MTP       , 0x9102, "WMDRMPD_GetSecureTimeResponse"},
    {USB_PTP_FLAVOR_CANON     , 0x9102, "GetStorageInfo"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9103, "SelfCleaning"},
    {USB_PTP_FLAVOR_MTP       , 0x9103, "WMDRMPD_SetLicenseResponse"},
    {USB_PTP_FLAVOR_CANON     , 0x9103, "GetObjectInfo"},
    {USB_PTP_FLAVOR_MTP       , 0x9104, "WMDRMPD_GetSyncList"},
    {USB_PTP_FLAVOR_CANON     , 0x9104, "GetObject"},
    {USB_PTP_FLAVOR_MTP       , 0x9105, "WMDRMPD_SendMeterChallengeQuery"},
    {USB_PTP_FLAVOR_CANON     , 0x9105, "DeleteObject"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9106, "SetRGBGain"},
    {USB_PTP_FLAVOR_MTP       , 0x9106, "WMDRMPD_GetMeterChallenge"},
    {USB_PTP_FLAVOR_CANON     , 0x9106, "FormatStore"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9107, "SetPresetMode"},
    {USB_PTP_FLAVOR_CANON     , 0x9107, "GetPartialObject"},
    {USB_PTP_FLAVOR_MTP       , 0x9107, "WMDRMPD_SetMeterResponse"},
    {USB_PTP_FLAVOR_MTP       , 0x9108, "WMDRMPD_CleanDataStore"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9108, "SetWBBiasAll"},
    {USB_PTP_FLAVOR_CANON     , 0x9108, "GetDeviceInfoEx"},
    {USB_PTP_FLAVOR_CANON     , 0x9109, "GetObjectInfoEx"},
    {USB_PTP_FLAVOR_MTP       , 0x9109, "WMDRMPD_GetLicenseState"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x910a, "GetCameraControlMode"},
    {USB_PTP_FLAVOR_MTP       , 0x910a, "WMDRMPD_SendWMDRMPDCommand"},
    {USB_PTP_FLAVOR_CANON     , 0x910a, "GetThumbEx"},
    {USB_PTP_FLAVOR_MTP       , 0x910b, "WMDRMPD_SendWMDRMPDRequest"},
    {USB_PTP_FLAVOR_CANON     , 0x910b, "SendPartialObject"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x910b, "SetCameraControlMode"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x910c, "SetWBRGBGain"},
    {USB_PTP_FLAVOR_CANON     , 0x910c, "SetObjectAttributes"},
    {USB_PTP_FLAVOR_CANON     , 0x910d, "GetObjectTime"},
    {USB_PTP_FLAVOR_CANON     , 0x910e, "SetObjectTime"},
    {USB_PTP_FLAVOR_CANON     , 0x910f, "RemoteRelease"},
    {USB_PTP_FLAVOR_CANON     , 0x9110, "SetDevicePropValueEx"},
    {USB_PTP_FLAVOR_CANON     , 0x9113, "GetRemoteMode"},
    {USB_PTP_FLAVOR_CANON     , 0x9114, "SetRemoteMode"},
    {USB_PTP_FLAVOR_CANON     , 0x9115, "SetEventMode"},
    {USB_PTP_FLAVOR_CANON     , 0x9116, "GetEvent"},
    {USB_PTP_FLAVOR_CANON     , 0x9117, "TransferComplete"},
    {USB_PTP_FLAVOR_CANON     , 0x9118, "CancelTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0x9119, "ResetTransfer"},
    {USB_PTP_FLAVOR_CANON     , 0x911a, "PCHDDCapacity"},
    {USB_PTP_FLAVOR_CANON     , 0x911b, "SetUILock"},
    {USB_PTP_FLAVOR_CANON     , 0x911c, "ResetUILock"},
    {USB_PTP_FLAVOR_CANON     , 0x911d, "KeepDeviceOn"},
    {USB_PTP_FLAVOR_CANON     , 0x911e, "SetNullPacketMode"},
    {USB_PTP_FLAVOR_CANON     , 0x911f, "UpdateFirmware"},
    {USB_PTP_FLAVOR_CANON     , 0x9120, "TransferCompleteDT"},
    {USB_PTP_FLAVOR_CANON     , 0x9121, "CancelTransferDT"},
    {USB_PTP_FLAVOR_CANON     , 0x9122, "SetWftProfile"},
    {USB_PTP_FLAVOR_MTP       , 0x9122, "WPDWCN_ProcessWFCObject"},
    {USB_PTP_FLAVOR_CANON     , 0x9122, "GetWftProfile"},
    {USB_PTP_FLAVOR_CANON     , 0x9124, "SetProfileToWft"},
    {USB_PTP_FLAVOR_CANON     , 0x9125, "BulbStart"},
    {USB_PTP_FLAVOR_CANON     , 0x9126, "BulbEnd"},
    {USB_PTP_FLAVOR_CANON     , 0x9127, "RequestDevicePropValue"},
    {USB_PTP_FLAVOR_CANON     , 0x9128, "RemoteReleaseOn"},
    {USB_PTP_FLAVOR_CANON     , 0x9129, "RemoteReleaseOff"},
    {USB_PTP_FLAVOR_CANON     , 0x9151, "InitiateViewfinder"},
    {USB_PTP_FLAVOR_CANON     , 0x9152, "TerminateViewfinder"},
    {USB_PTP_FLAVOR_CANON     , 0x9153, "GetViewFinderData"},
    {USB_PTP_FLAVOR_CANON     , 0x9154, "DoAf"},
    {USB_PTP_FLAVOR_CANON     , 0x9155, "DriveLens"},
    {USB_PTP_FLAVOR_CANON     , 0x9156, "DepthOfFieldPreview"},
    {USB_PTP_FLAVOR_CANON     , 0x9157, "ClickWB"},
    {USB_PTP_FLAVOR_CANON     , 0x9158, "Zoom"},
    {USB_PTP_FLAVOR_CANON     , 0x9159, "ZoomPosition"},
    {USB_PTP_FLAVOR_CANON     , 0x915a, "SetLiveAfFrame"},
    {USB_PTP_FLAVOR_CANON     , 0x9160, "AfCancel"},
    {USB_PTP_FLAVOR_MTP       , 0x9170, "AAVT_OpenMediaSession"},
    {USB_PTP_FLAVOR_MTP       , 0x9171, "AAVT_CloseMediaSession"},
    {USB_PTP_FLAVOR_MTP       , 0x9172, "AAVT_GetNextDataBlock"},
    {USB_PTP_FLAVOR_MTP       , 0x9173, "AAVT_SetCurrentTimePosition"},
    {USB_PTP_FLAVOR_MTP       , 0x9180, "WMDRMND_SendRegistrationRequest"},
    {USB_PTP_FLAVOR_MTP       , 0x9181, "WMDRMND_GetRegistrationResponse"},
    {USB_PTP_FLAVOR_MTP       , 0x9182, "WMDRMND_GetProximityChallenge"},
    {USB_PTP_FLAVOR_MTP       , 0x9183, "WMDRMND_SendProximityResponse"},
    {USB_PTP_FLAVOR_MTP       , 0x9184, "WMDRMND_SendWMDRMNDLicenseRequest"},
    {USB_PTP_FLAVOR_MTP       , 0x9185, "WMDRMND_GetWMDRMNDLicenseResponse"},
    {USB_PTP_FLAVOR_CANON     , 0x91fe, "FAPIMessageTX"},
    {USB_PTP_FLAVOR_CANON     , 0x91ff, "FAPIMessageRX"},
    {USB_PTP_FLAVOR_NIKON     , 0x9200, "GetPreviewImg"},
    {USB_PTP_FLAVOR_NIKON     , 0x9201, "StartLiveView"},
    {USB_PTP_FLAVOR_MTP       , 0x9201, "WMPPD_ReportAddedDeletedItems"},
    {USB_PTP_FLAVOR_NIKON     , 0x9202, "EndLiveView"},
    {USB_PTP_FLAVOR_MTP       , 0x9202, "WMPPD_ReportAcquiredItems"},
    {USB_PTP_FLAVOR_NIKON     , 0x9203, "GetLiveViewImg"},
    {USB_PTP_FLAVOR_MTP       , 0x9203, "WMPPD_PlaylistObjectPref"},
    {USB_PTP_FLAVOR_MTP       , 0x9204, "ZUNE_GETUNDEFINED001"},
    {USB_PTP_FLAVOR_NIKON     , 0x9204, "MfDrive"},
    {USB_PTP_FLAVOR_NIKON     , 0x9205, "ChangeAfArea"},
    {USB_PTP_FLAVOR_NIKON     , 0x9206, "AfDriveCancel"},
    {USB_PTP_FLAVOR_MTP       , 0x9212, "WMDRMPD_SendWMDRMPDAppRequest"},
    {USB_PTP_FLAVOR_MTP       , 0x9213, "WMDRMPD_GetWMDRMPDAppResponse"},
    {USB_PTP_FLAVOR_MTP       , 0x9214, "WMDRMPD_EnableTrustedFilesOperations"},
    {USB_PTP_FLAVOR_MTP       , 0x9215, "WMDRMPD_DisableTrustedFilesOperations"},
    {USB_PTP_FLAVOR_MTP       , 0x9216, "WMDRMPD_EndTrustedAppSession"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9301, "GetDeviceInfo"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9302, "Init1"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9402, "SetDateTime"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9482, "GetDateTime"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9501, "SetCameraID"},
    {USB_PTP_FLAVOR_OLYMPUS   , 0x9581, "GetCameraID"},
    {USB_PTP_FLAVOR_ANDROID   , 0x95c1, "GetPartialObject64"},
    {USB_PTP_FLAVOR_ANDROID   , 0x95c2, "SendPartialObject"},
    {USB_PTP_FLAVOR_ANDROID   , 0x95c3, "TruncateObject"},
    {USB_PTP_FLAVOR_ANDROID   , 0x95c4, "BeginEditObject"},
    {USB_PTP_FLAVOR_ANDROID   , 0x95c5, "EndEditObject"},
    {USB_PTP_FLAVOR_MTP       , 0x9801, "GetObjectPropsSupported"},
    {USB_PTP_FLAVOR_MTP       , 0x9802, "GetObjectPropDesc"},
    {USB_PTP_FLAVOR_MTP       , 0x9803, "GetObjectPropValue"},
    {USB_PTP_FLAVOR_MTP       , 0x9804, "SetObjectPropValue"},
    {USB_PTP_FLAVOR_MTP       , 0x9805, "GetObjPropList"},
    {USB_PTP_FLAVOR_MTP       , 0x9806, "SetObjPropList"},
    {USB_PTP_FLAVOR_MTP       , 0x9807, "GetInterdependendPropdesc"},
    {USB_PTP_FLAVOR_MTP       , 0x9808, "SendObjectPropList"},
    {USB_PTP_FLAVOR_MTP       , 0x9810, "GetObjectReferences"},
    {USB_PTP_FLAVOR_MTP       , 0x9811, "SetObjectReferences"},
    {USB_PTP_FLAVOR_MTP       , 0x9812, "UpdateDeviceFirmware"},
    {USB_PTP_FLAVOR_MTP       , 0x9820, "Skip"},
    {USB_PTP_FLAVOR_CANON     , 0x9999, "CHDK"},
    {USB_PTP_FLAVOR_ALL       , 0x1003, "CloseSession"},
    {USB_PTP_FLAVOR_ALL       , 0xf000, "EXTENSION_MASK"},
    /* START Manually added Entries */
    {USB_PTP_FLAVOR_NIKON     , 0xfc01, "ServiceModeStart"},
    {USB_PTP_FLAVOR_NIKON     , 0xfc02, "ServiceModeStop"},
    /* END Manually added Entries */
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_OFC Object Format Codes */
static const value_string_masked_t usb_ptp_ofc_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x3000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x3001, "Association"},
    {USB_PTP_FLAVOR_ALL       , 0x3002, "Script"},
    {USB_PTP_FLAVOR_ALL       , 0x3003, "Executable"},
    {USB_PTP_FLAVOR_ALL       , 0x3004, "Text"},
    {USB_PTP_FLAVOR_ALL       , 0x3005, "HTML"},
    {USB_PTP_FLAVOR_ALL       , 0x3006, "DPOF"},
    {USB_PTP_FLAVOR_ALL       , 0x3007, "AIFF"},
    {USB_PTP_FLAVOR_ALL       , 0x3008, "WAV"},
    {USB_PTP_FLAVOR_ALL       , 0x3009, "MP3"},
    {USB_PTP_FLAVOR_ALL       , 0x300a, "AVI"},
    {USB_PTP_FLAVOR_ALL       , 0x300b, "MPEG"},
    {USB_PTP_FLAVOR_ALL       , 0x300c, "ASF"},
    {USB_PTP_FLAVOR_ALL       , 0x300d, "MOV"},
    {USB_PTP_FLAVOR_ALL       , 0x3800, "UnknownImage"},
    {USB_PTP_FLAVOR_ALL       , 0x3801, "EXIF_JPEG"},
    {USB_PTP_FLAVOR_ALL       , 0x3802, "TIFF_EP"},
    {USB_PTP_FLAVOR_ALL       , 0x3803, "FlashPix"},
    {USB_PTP_FLAVOR_ALL       , 0x3804, "BMP"},
    {USB_PTP_FLAVOR_ALL       , 0x3805, "CIFF"},
    {USB_PTP_FLAVOR_ALL       , 0x3807, "GIF"},
    {USB_PTP_FLAVOR_ALL       , 0x3808, "JFIF"},
    {USB_PTP_FLAVOR_ALL       , 0x3809, "PCD"},
    {USB_PTP_FLAVOR_ALL       , 0x380a, "PICT"},
    {USB_PTP_FLAVOR_ALL       , 0x380b, "PNG"},
    {USB_PTP_FLAVOR_ALL       , 0x380d, "TIFF"},
    {USB_PTP_FLAVOR_ALL       , 0x380e, "TIFF_IT"},
    {USB_PTP_FLAVOR_ALL       , 0x380f, "JP2"},
    {USB_PTP_FLAVOR_ALL       , 0x3810, "JPX"},
    {USB_PTP_FLAVOR_ALL       , 0x3811, "DNG"},
    {USB_PTP_FLAVOR_KODAK     , 0xb002, "M3U"},
    {USB_PTP_FLAVOR_CANON     , 0xb101, "CRW"},
    {USB_PTP_FLAVOR_CANON     , 0xb103, "CRW3"},
    {USB_PTP_FLAVOR_CANON     , 0xb104, "MOV"},
    {USB_PTP_FLAVOR_CANON     , 0xb105, "MOV2"},
    {USB_PTP_FLAVOR_CANON     , 0xb1ff, "CHDK_CRW"},
    {USB_PTP_FLAVOR_MTP       , 0xb211, "MediaCard"},
    {USB_PTP_FLAVOR_MTP       , 0xb212, "MediaCardGroup"},
    {USB_PTP_FLAVOR_MTP       , 0xb213, "Encounter"},
    {USB_PTP_FLAVOR_MTP       , 0xb214, "EncounterBox"},
    {USB_PTP_FLAVOR_MTP       , 0xb215, "M4A"},
    {USB_PTP_FLAVOR_MTP       , 0xb217, "ZUNEUNDEFINED"},
    {USB_PTP_FLAVOR_MTP       , 0xb802, "Firmware"},
    {USB_PTP_FLAVOR_MTP       , 0xb881, "WindowsImageFormat"},
    {USB_PTP_FLAVOR_MTP       , 0xb900, "UndefinedAudio"},
    {USB_PTP_FLAVOR_MTP       , 0xb901, "WMA"},
    {USB_PTP_FLAVOR_MTP       , 0xb902, "OGG"},
    {USB_PTP_FLAVOR_MTP       , 0xb903, "AAC"},
    {USB_PTP_FLAVOR_MTP       , 0xb904, "AudibleCodec"},
    {USB_PTP_FLAVOR_MTP       , 0xb906, "FLAC"},
    {USB_PTP_FLAVOR_MTP       , 0xb980, "UndefinedVideo"},
    {USB_PTP_FLAVOR_MTP       , 0xb909, "SamsungPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xb981, "WMV"},
    {USB_PTP_FLAVOR_MTP       , 0xb982, "MP4"},
    {USB_PTP_FLAVOR_MTP       , 0xb983, "MP2"},
    {USB_PTP_FLAVOR_MTP       , 0xb984, "3GP"},
    {USB_PTP_FLAVOR_MTP       , 0xba00, "UndefinedCollection"},
    {USB_PTP_FLAVOR_MTP       , 0xba01, "AbstractMultimediaAlbum"},
    {USB_PTP_FLAVOR_MTP       , 0xba02, "AbstractImageAlbum"},
    {USB_PTP_FLAVOR_MTP       , 0xba03, "AbstractAudioAlbum"},
    {USB_PTP_FLAVOR_MTP       , 0xba04, "AbstractVideoAlbum"},
    {USB_PTP_FLAVOR_MTP       , 0xba05, "AbstractAudioVideoPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba06, "AbstractContactGroup"},
    {USB_PTP_FLAVOR_MTP       , 0xba07, "AbstractMessageFolder"},
    {USB_PTP_FLAVOR_MTP       , 0xba08, "AbstractChapteredProduction"},
    {USB_PTP_FLAVOR_MTP       , 0xba09, "AbstractAudioPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba0a, "AbstractVideoPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba0b, "AbstractMediacast"},
    {USB_PTP_FLAVOR_MTP       , 0xba10, "WPLPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba11, "M3UPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba12, "MPLPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba13, "ASXPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba14, "PLSPlaylist"},
    {USB_PTP_FLAVOR_MTP       , 0xba80, "UndefinedDocument"},
    {USB_PTP_FLAVOR_MTP       , 0xba81, "AbstractDocument"},
    {USB_PTP_FLAVOR_MTP       , 0xba82, "XMLDocument"},
    {USB_PTP_FLAVOR_MTP       , 0xba83, "MSWordDocument"},
    {USB_PTP_FLAVOR_MTP       , 0xba84, "MHTCompiledHTMLDocument"},
    {USB_PTP_FLAVOR_MTP       , 0xba85, "MSExcelSpreadsheetXLS"},
    {USB_PTP_FLAVOR_MTP       , 0xba86, "MSPowerpointPresentationPPT"},
    {USB_PTP_FLAVOR_MTP       , 0xbb00, "UndefinedMessage"},
    {USB_PTP_FLAVOR_MTP       , 0xbb01, "AbstractMessage"},
    {USB_PTP_FLAVOR_MTP       , 0xbb80, "UndefinedContact"},
    {USB_PTP_FLAVOR_MTP       , 0xbb81, "AbstractContact"},
    {USB_PTP_FLAVOR_MTP       , 0xbb82, "vCard2"},
    {USB_PTP_FLAVOR_MTP       , 0xbb83, "vCard3"},
    {USB_PTP_FLAVOR_MTP       , 0xbe00, "UndefinedCalendarItem"},
    {USB_PTP_FLAVOR_MTP       , 0xbe01, "AbstractCalendarItem"},
    {USB_PTP_FLAVOR_MTP       , 0xbe02, "vCalendar1"},
    {USB_PTP_FLAVOR_MTP       , 0xbe03, "vCalendar2"},
    {USB_PTP_FLAVOR_MTP       , 0xbe80, "UndefinedWindowsExecutable"},
    {USB_PTP_FLAVOR_MTP       , 0xbe81, "MediaCast"},
    {USB_PTP_FLAVOR_MTP       , 0xbe82, "Section"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_OPC MTP Object Properties */
static const value_string_masked_t usb_ptp_opc_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0xb104, "WirelessConfigurationFile"},
    {USB_PTP_FLAVOR_ALL       , 0xd901, "BuyFlag"},
    {USB_PTP_FLAVOR_ALL       , 0xdc01, "StorageID"},
    {USB_PTP_FLAVOR_ALL       , 0xdc02, "ObjectFormat"},
    {USB_PTP_FLAVOR_ALL       , 0xdc03, "ProtectionStatus"},
    {USB_PTP_FLAVOR_ALL       , 0xdc04, "ObjectSize"},
    {USB_PTP_FLAVOR_ALL       , 0xdc05, "AssociationType"},
    {USB_PTP_FLAVOR_ALL       , 0xdc06, "AssociationDesc"},
    {USB_PTP_FLAVOR_ALL       , 0xdc07, "ObjectFileName"},
    {USB_PTP_FLAVOR_ALL       , 0xdc08, "DateCreated"},
    {USB_PTP_FLAVOR_ALL       , 0xdc09, "DateModified"},
    {USB_PTP_FLAVOR_ALL       , 0xdc0a, "Keywords"},
    {USB_PTP_FLAVOR_ALL       , 0xdc0b, "ParentObject"},
    {USB_PTP_FLAVOR_ALL       , 0xdc0c, "AllowedFolderContents"},
    {USB_PTP_FLAVOR_ALL       , 0xdc0d, "Hidden"},
    {USB_PTP_FLAVOR_ALL       , 0xdc0e, "SystemObject"},
    {USB_PTP_FLAVOR_ALL       , 0xdc41, "PersistantUniqueObjectIdentifier"},
    {USB_PTP_FLAVOR_ALL       , 0xdc42, "SyncID"},
    {USB_PTP_FLAVOR_ALL       , 0xdc43, "PropertyBag"},
    {USB_PTP_FLAVOR_ALL       , 0xdc44, "Name"},
    {USB_PTP_FLAVOR_ALL       , 0xdc45, "CreatedBy"},
    {USB_PTP_FLAVOR_ALL       , 0xdc46, "Artist"},
    {USB_PTP_FLAVOR_ALL       , 0xdc47, "DateAuthored"},
    {USB_PTP_FLAVOR_ALL       , 0xdc48, "Description"},
    {USB_PTP_FLAVOR_ALL       , 0xdc49, "URLReference"},
    {USB_PTP_FLAVOR_ALL       , 0xdc4a, "LanguageLocale"},
    {USB_PTP_FLAVOR_ALL       , 0xdc4b, "CopyrightInformation"},
    {USB_PTP_FLAVOR_ALL       , 0xdc4c, "Source"},
    {USB_PTP_FLAVOR_ALL       , 0xdc4d, "OriginLocation"},
    {USB_PTP_FLAVOR_ALL       , 0xdc4e, "DateAdded"},
    {USB_PTP_FLAVOR_ALL       , 0xdc4f, "NonConsumable"},
    {USB_PTP_FLAVOR_ALL       , 0xdc50, "CorruptOrUnplayable"},
    {USB_PTP_FLAVOR_ALL       , 0xdc51, "ProducerSerialNumber"},
    {USB_PTP_FLAVOR_ALL       , 0xdc81, "RepresentativeSampleFormat"},
    {USB_PTP_FLAVOR_ALL       , 0xdc82, "RepresentativeSampleSize"},
    {USB_PTP_FLAVOR_ALL       , 0xdc83, "RepresentativeSampleHeight"},
    {USB_PTP_FLAVOR_ALL       , 0xdc84, "RepresentativeSampleWidth"},
    {USB_PTP_FLAVOR_ALL       , 0xdc85, "RepresentativeSampleDuration"},
    {USB_PTP_FLAVOR_ALL       , 0xdc86, "RepresentativeSampleData"},
    {USB_PTP_FLAVOR_ALL       , 0xdc87, "Width"},
    {USB_PTP_FLAVOR_ALL       , 0xdc88, "Height"},
    {USB_PTP_FLAVOR_ALL       , 0xdc89, "Duration"},
    {USB_PTP_FLAVOR_ALL       , 0xdc8a, "Rating"},
    {USB_PTP_FLAVOR_ALL       , 0xdc8b, "Track"},
    {USB_PTP_FLAVOR_ALL       , 0xdc8c, "Genre"},
    {USB_PTP_FLAVOR_ALL       , 0xdc8d, "Credits"},
    {USB_PTP_FLAVOR_ALL       , 0xdc8e, "Lyrics"},
    {USB_PTP_FLAVOR_ALL       , 0xdc8f, "SubscriptionContentID"},
    {USB_PTP_FLAVOR_ALL       , 0xdc90, "ProducedBy"},
    {USB_PTP_FLAVOR_ALL       , 0xdc91, "UseCount"},
    {USB_PTP_FLAVOR_ALL       , 0xdc92, "SkipCount"},
    {USB_PTP_FLAVOR_ALL       , 0xdc93, "LastAccessed"},
    {USB_PTP_FLAVOR_ALL       , 0xdc94, "ParentalRating"},
    {USB_PTP_FLAVOR_ALL       , 0xdc95, "MetaGenre"},
    {USB_PTP_FLAVOR_ALL       , 0xdc96, "Composer"},
    {USB_PTP_FLAVOR_ALL       , 0xdc97, "EffectiveRating"},
    {USB_PTP_FLAVOR_ALL       , 0xdc98, "Subtitle"},
    {USB_PTP_FLAVOR_ALL       , 0xdc99, "OriginalReleaseDate"},
    {USB_PTP_FLAVOR_ALL       , 0xdc9a, "AlbumName"},
    {USB_PTP_FLAVOR_ALL       , 0xdc9b, "AlbumArtist"},
    {USB_PTP_FLAVOR_ALL       , 0xdc9c, "Mood"},
    {USB_PTP_FLAVOR_ALL       , 0xdc9d, "DRMStatus"},
    {USB_PTP_FLAVOR_ALL       , 0xdc9e, "SubDescription"},
    {USB_PTP_FLAVOR_ALL       , 0xdcd1, "IsCropped"},
    {USB_PTP_FLAVOR_ALL       , 0xdcd2, "IsColorCorrected"},
    {USB_PTP_FLAVOR_ALL       , 0xdcd3, "ImageBitDepth"},
    {USB_PTP_FLAVOR_ALL       , 0xdcd4, "Fnumber"},
    {USB_PTP_FLAVOR_ALL       , 0xdcd5, "ExposureTime"},
    {USB_PTP_FLAVOR_ALL       , 0xdcd6, "ExposureIndex"},
    {USB_PTP_FLAVOR_ALL       , 0xdce0, "DisplayName"},
    {USB_PTP_FLAVOR_ALL       , 0xdce1, "BodyText"},
    {USB_PTP_FLAVOR_ALL       , 0xdce2, "Subject"},
    {USB_PTP_FLAVOR_ALL       , 0xdce3, "Priority"},
    {USB_PTP_FLAVOR_ALL       , 0xdd00, "GivenName"},
    {USB_PTP_FLAVOR_ALL       , 0xdd01, "MiddleNames"},
    {USB_PTP_FLAVOR_ALL       , 0xdd02, "FamilyName"},
    {USB_PTP_FLAVOR_ALL       , 0xdd03, "Prefix"},
    {USB_PTP_FLAVOR_ALL       , 0xdd04, "Suffix"},
    {USB_PTP_FLAVOR_ALL       , 0xdd05, "PhoneticGivenName"},
    {USB_PTP_FLAVOR_ALL       , 0xdd06, "PhoneticFamilyName"},
    {USB_PTP_FLAVOR_ALL       , 0xdd07, "EmailPrimary"},
    {USB_PTP_FLAVOR_ALL       , 0xdd08, "EmailPersonal1"},
    {USB_PTP_FLAVOR_ALL       , 0xdd09, "EmailPersonal2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd0a, "EmailBusiness1"},
    {USB_PTP_FLAVOR_ALL       , 0xdd0b, "EmailBusiness2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd0c, "EmailOthers"},
    {USB_PTP_FLAVOR_ALL       , 0xdd0d, "PhoneNumberPrimary"},
    {USB_PTP_FLAVOR_ALL       , 0xdd0e, "PhoneNumberPersonal"},
    {USB_PTP_FLAVOR_ALL       , 0xdd0f, "PhoneNumberPersonal2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd10, "PhoneNumberBusiness"},
    {USB_PTP_FLAVOR_ALL       , 0xdd11, "PhoneNumberBusiness2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd12, "PhoneNumberMobile"},
    {USB_PTP_FLAVOR_ALL       , 0xdd13, "PhoneNumberMobile2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd14, "FaxNumberPrimary"},
    {USB_PTP_FLAVOR_ALL       , 0xdd15, "FaxNumberPersonal"},
    {USB_PTP_FLAVOR_ALL       , 0xdd16, "FaxNumberBusiness"},
    {USB_PTP_FLAVOR_ALL       , 0xdd17, "PagerNumber"},
    {USB_PTP_FLAVOR_ALL       , 0xdd18, "PhoneNumberOthers"},
    {USB_PTP_FLAVOR_ALL       , 0xdd19, "PrimaryWebAddress"},
    {USB_PTP_FLAVOR_ALL       , 0xdd1a, "PersonalWebAddress"},
    {USB_PTP_FLAVOR_ALL       , 0xdd1b, "BusinessWebAddress"},
    {USB_PTP_FLAVOR_ALL       , 0xdd1c, "InstantMessengerAddress"},
    {USB_PTP_FLAVOR_ALL       , 0xdd1d, "InstantMessengerAddress2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd1e, "InstantMessengerAddress3"},
    {USB_PTP_FLAVOR_ALL       , 0xdd1f, "PostalAddressPersonalFull"},
    {USB_PTP_FLAVOR_ALL       , 0xdd20, "PostalAddressPersonalFullLine1"},
    {USB_PTP_FLAVOR_ALL       , 0xdd21, "PostalAddressPersonalFullLine2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd22, "PostalAddressPersonalFullCity"},
    {USB_PTP_FLAVOR_ALL       , 0xdd23, "PostalAddressPersonalFullRegion"},
    {USB_PTP_FLAVOR_ALL       , 0xdd24, "PostalAddressPersonalFullPostalCode"},
    {USB_PTP_FLAVOR_ALL       , 0xdd25, "PostalAddressPersonalFullCountry"},
    {USB_PTP_FLAVOR_ALL       , 0xdd26, "PostalAddressBusinessFull"},
    {USB_PTP_FLAVOR_ALL       , 0xdd27, "PostalAddressBusinessLine1"},
    {USB_PTP_FLAVOR_ALL       , 0xdd28, "PostalAddressBusinessLine2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd29, "PostalAddressBusinessCity"},
    {USB_PTP_FLAVOR_ALL       , 0xdd2a, "PostalAddressBusinessRegion"},
    {USB_PTP_FLAVOR_ALL       , 0xdd2b, "PostalAddressBusinessPostalCode"},
    {USB_PTP_FLAVOR_ALL       , 0xdd2c, "PostalAddressBusinessCountry"},
    {USB_PTP_FLAVOR_ALL       , 0xdd2d, "PostalAddressOtherFull"},
    {USB_PTP_FLAVOR_ALL       , 0xdd2e, "PostalAddressOtherLine1"},
    {USB_PTP_FLAVOR_ALL       , 0xdd2f, "PostalAddressOtherLine2"},
    {USB_PTP_FLAVOR_ALL       , 0xdd30, "PostalAddressOtherCity"},
    {USB_PTP_FLAVOR_ALL       , 0xdd31, "PostalAddressOtherRegion"},
    {USB_PTP_FLAVOR_ALL       , 0xdd32, "PostalAddressOtherPostalCode"},
    {USB_PTP_FLAVOR_ALL       , 0xdd33, "PostalAddressOtherCountry"},
    {USB_PTP_FLAVOR_ALL       , 0xdd34, "OrganizationName"},
    {USB_PTP_FLAVOR_ALL       , 0xdd35, "PhoneticOrganizationName"},
    {USB_PTP_FLAVOR_ALL       , 0xdd36, "Role"},
    {USB_PTP_FLAVOR_ALL       , 0xdd37, "Birthdate"},
    {USB_PTP_FLAVOR_ALL       , 0xdd40, "MessageTo"},
    {USB_PTP_FLAVOR_ALL       , 0xdd41, "MessageCC"},
    {USB_PTP_FLAVOR_ALL       , 0xdd42, "MessageBCC"},
    {USB_PTP_FLAVOR_ALL       , 0xdd43, "MessageRead"},
    {USB_PTP_FLAVOR_ALL       , 0xdd44, "MessageReceivedTime"},
    {USB_PTP_FLAVOR_ALL       , 0xdd45, "MessageSender"},
    {USB_PTP_FLAVOR_ALL       , 0xdd50, "ActivityBeginTime"},
    {USB_PTP_FLAVOR_ALL       , 0xdd51, "ActivityEndTime"},
    {USB_PTP_FLAVOR_ALL       , 0xdd52, "ActivityLocation"},
    {USB_PTP_FLAVOR_ALL       , 0xdd54, "ActivityRequiredAttendees"},
    {USB_PTP_FLAVOR_ALL       , 0xdd55, "ActivityOptionalAttendees"},
    {USB_PTP_FLAVOR_ALL       , 0xdd56, "ActivityResources"},
    {USB_PTP_FLAVOR_ALL       , 0xdd57, "ActivityAccepted"},
    {USB_PTP_FLAVOR_ALL       , 0xdd5d, "Owner"},
    {USB_PTP_FLAVOR_ALL       , 0xdd5e, "Editor"},
    {USB_PTP_FLAVOR_ALL       , 0xdd5f, "Webmaster"},
    {USB_PTP_FLAVOR_ALL       , 0xdd60, "URLSource"},
    {USB_PTP_FLAVOR_ALL       , 0xdd61, "URLDestination"},
    {USB_PTP_FLAVOR_ALL       , 0xdd62, "TimeBookmark"},
    {USB_PTP_FLAVOR_ALL       , 0xdd63, "ObjectBookmark"},
    {USB_PTP_FLAVOR_ALL       , 0xdd64, "ByteBookmark"},
    {USB_PTP_FLAVOR_ALL       , 0xdd70, "LastBuildDate"},
    {USB_PTP_FLAVOR_ALL       , 0xdd71, "TimetoLive"},
    {USB_PTP_FLAVOR_ALL       , 0xdd72, "MediaGUID"},
    {USB_PTP_FLAVOR_ALL       , 0xde91, "TotalBitRate"},
    {USB_PTP_FLAVOR_ALL       , 0xde92, "BitRateType"},
    {USB_PTP_FLAVOR_ALL       , 0xde93, "SampleRate"},
    {USB_PTP_FLAVOR_ALL       , 0xde94, "NumberOfChannels"},
    {USB_PTP_FLAVOR_ALL       , 0xde95, "AudioBitDepth"},
    {USB_PTP_FLAVOR_ALL       , 0xde97, "ScanDepth"},
    {USB_PTP_FLAVOR_ALL       , 0xde99, "AudioWAVECodec"},
    {USB_PTP_FLAVOR_ALL       , 0xde9a, "AudioBitRate"},
    {USB_PTP_FLAVOR_ALL       , 0xde9b, "VideoFourCCCodec"},
    {USB_PTP_FLAVOR_ALL       , 0xde9c, "VideoBitRate"},
    {USB_PTP_FLAVOR_ALL       , 0xde9d, "FramesPerThousandSeconds"},
    {USB_PTP_FLAVOR_ALL       , 0xde9e, "KeyFrameDistance"},
    {USB_PTP_FLAVOR_ALL       , 0xde9f, "BufferSize"},
    {USB_PTP_FLAVOR_ALL       , 0xdea0, "EncodingQuality"},
    {USB_PTP_FLAVOR_ALL       , 0xdea1, "EncodingProfile"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_OPFF MTP Device Property Codes */
static const value_string_masked_t usb_ptp_opff_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x00, "None"},
    {USB_PTP_FLAVOR_ALL       , 0x01, "Range"},
    {USB_PTP_FLAVOR_ALL       , 0x02, "Enumeration"},
    {USB_PTP_FLAVOR_ALL       , 0x03, "DateTime"},
    {USB_PTP_FLAVOR_ALL       , 0x04, "FixedLengthArray"},
    {USB_PTP_FLAVOR_ALL       , 0x05, "RegularExpression"},
    {USB_PTP_FLAVOR_ALL       , 0x06, "ByteArray"},
    {USB_PTP_FLAVOR_ALL       , 0xff, "LongString"},
    {USB_PTP_FLAVOR_NONE      , 0x00, NULL}
};
/* PTP_PS Protection Status */
static const value_string_masked_t usb_ptp_ps_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x0000, "NoProtection"},
    {USB_PTP_FLAVOR_ALL       , 0x0001, "ReadOnly"},
    {USB_PTP_FLAVOR_MTP       , 0x8002, "ReadOnlyData"},
    {USB_PTP_FLAVOR_MTP       , 0x8003, "NonTransferableData"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_RC Response Codes */
static const value_string_masked_t usb_ptp_rc_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x2000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x2001, "OK"},
    {USB_PTP_FLAVOR_ALL       , 0x2002, "GeneralError"},
    {USB_PTP_FLAVOR_ALL       , 0x2003, "SessionNotOpen"},
    {USB_PTP_FLAVOR_ALL       , 0x2004, "InvalidTransactionID"},
    {USB_PTP_FLAVOR_ALL       , 0x2005, "OperationNotSupported"},
    {USB_PTP_FLAVOR_ALL       , 0x2006, "ParameterNotSupported"},
    {USB_PTP_FLAVOR_ALL       , 0x2007, "IncompleteTransfer"},
    {USB_PTP_FLAVOR_ALL       , 0x2008, "InvalidStorageId"},
    {USB_PTP_FLAVOR_ALL       , 0x2009, "InvalidObjectHandle"},
    {USB_PTP_FLAVOR_ALL       , 0x200a, "DevicePropNotSupported"},
    {USB_PTP_FLAVOR_ALL       , 0x200b, "InvalidObjectFormatCode"},
    {USB_PTP_FLAVOR_ALL       , 0x200c, "StoreFull"},
    {USB_PTP_FLAVOR_ALL       , 0x200d, "ObjectWriteProtected"},
    {USB_PTP_FLAVOR_ALL       , 0x200e, "StoreReadOnly"},
    {USB_PTP_FLAVOR_ALL       , 0x200f, "AccessDenied"},
    {USB_PTP_FLAVOR_ALL       , 0x2010, "NoThumbnailPresent"},
    {USB_PTP_FLAVOR_ALL       , 0x2011, "SelfTestFailed"},
    {USB_PTP_FLAVOR_ALL       , 0x2012, "PartialDeletion"},
    {USB_PTP_FLAVOR_ALL       , 0x2013, "StoreNotAvailable"},
    {USB_PTP_FLAVOR_ALL       , 0x2014, "SpecificationByFormatUnsupported"},
    {USB_PTP_FLAVOR_ALL       , 0x2015, "NoValidObjectInfo"},
    {USB_PTP_FLAVOR_ALL       , 0x2016, "InvalidCodeFormat"},
    {USB_PTP_FLAVOR_ALL       , 0x2017, "UnknownVendorCode"},
    {USB_PTP_FLAVOR_ALL       , 0x2018, "CaptureAlreadyTerminated"},
    {USB_PTP_FLAVOR_ALL       , 0x2019, "DeviceBusy"},
    {USB_PTP_FLAVOR_ALL       , 0x201a, "InvalidParentObject"},
    {USB_PTP_FLAVOR_ALL       , 0x201b, "InvalidDevicePropFormat"},
    {USB_PTP_FLAVOR_ALL       , 0x201c, "InvalidDevicePropValue"},
    {USB_PTP_FLAVOR_ALL       , 0x201d, "InvalidParameter"},
    {USB_PTP_FLAVOR_ALL       , 0x201e, "SessionAlreadyOpened"},
    {USB_PTP_FLAVOR_ALL       , 0x201f, "TransactionCanceled"},
    {USB_PTP_FLAVOR_ALL       , 0x2020, "SpecificationOfDestinationUnsupported"},
    {USB_PTP_FLAVOR_ALL       , 0x2021, "InvalidEnumHandle"},
    {USB_PTP_FLAVOR_ALL       , 0x2022, "NoStreamEnabled"},
    {USB_PTP_FLAVOR_ALL       , 0x2023, "InvalidDataSet"},
    {USB_PTP_FLAVOR_CANON     , 0xa001, "UNKNOWN_COMMAND"},
    {USB_PTP_FLAVOR_KODAK     , 0xa001, "FilenameRequired"},
    {USB_PTP_FLAVOR_NIKON     , 0xa001, "HardwareError"},
    {USB_PTP_FLAVOR_KODAK     , 0xa002, "FilenameConflicts"},
    {USB_PTP_FLAVOR_NIKON     , 0xa002, "OutOfFocus"},
    {USB_PTP_FLAVOR_KODAK     , 0xa003, "FilenameInvalid"},
    {USB_PTP_FLAVOR_NIKON     , 0xa003, "ChangeCameraModeFailed"},
    {USB_PTP_FLAVOR_NIKON     , 0xa004, "InvalidStatus"},
    {USB_PTP_FLAVOR_CANON     , 0xa005, "OPERATION_REFUSED"},
    {USB_PTP_FLAVOR_NIKON     , 0xa005, "SetPropertyNotSupported"},
    {USB_PTP_FLAVOR_CANON     , 0xa006, "LENS_COVER"},
    {USB_PTP_FLAVOR_NIKON     , 0xa006, "WbResetError"},
    {USB_PTP_FLAVOR_NIKON     , 0xa007, "DustReferenceError"},
    {USB_PTP_FLAVOR_NIKON     , 0xa008, "ShutterSpeedBulb"},
    {USB_PTP_FLAVOR_NIKON     , 0xa009, "MirrorUpSequence"},
    {USB_PTP_FLAVOR_NIKON     , 0xa00a, "CameraModeNotAdjustFNumber"},
    {USB_PTP_FLAVOR_NIKON     , 0xa00b, "NotLiveView"},
    {USB_PTP_FLAVOR_NIKON     , 0xa00c, "MfDriveStepEnd"},
    {USB_PTP_FLAVOR_NIKON     , 0xa00e, "MfDriveStepInsufficiency"},
    {USB_PTP_FLAVOR_CANON     , 0xa101, "BATTERY_LOW"},
    {USB_PTP_FLAVOR_CANON     , 0xa102, "NOT_READY"},
    {USB_PTP_FLAVOR_MTP       , 0xa121, "Invalid_WFC_Syntax"},
    {USB_PTP_FLAVOR_MTP       , 0xa122, "WFC_Version_Not_Supported"},
    {USB_PTP_FLAVOR_MTP       , 0xa170, "Invalid_Media_Session_ID"},
    {USB_PTP_FLAVOR_MTP       , 0xa171, "Media_Session_Limit_Reached"},
    {USB_PTP_FLAVOR_MTP       , 0xa172, "No_More_Data"},
    {USB_PTP_FLAVOR_MTP       , 0xa800, "Undefined"},
    {USB_PTP_FLAVOR_MTP       , 0xa801, "Invalid_ObjectPropCode"},
    {USB_PTP_FLAVOR_MTP       , 0xa802, "Invalid_ObjectProp_Format"},
    {USB_PTP_FLAVOR_MTP       , 0xa803, "Invalid_ObjectProp_Value"},
    {USB_PTP_FLAVOR_MTP       , 0xa804, "Invalid_ObjectReference"},
    {USB_PTP_FLAVOR_MTP       , 0xa806, "Invalid_Dataset"},
    {USB_PTP_FLAVOR_MTP       , 0xa807, "Specification_By_Group_Unsupported"},
    {USB_PTP_FLAVOR_MTP       , 0xa808, "Specification_By_Depth_Unsupported"},
    {USB_PTP_FLAVOR_MTP       , 0xa809, "Object_Too_Large"},
    {USB_PTP_FLAVOR_MTP       , 0xa80a, "ObjectProp_Not_Supported"},
    {USB_PTP_FLAVOR_NIKON     , 0xa022, "AdvancedTransferCancel"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};
/* PTP_ST Storage Types */
static const value_string_masked_t usb_ptp_st_mvals[] = {
    {USB_PTP_FLAVOR_ALL       , 0x0000, "Undefined"},
    {USB_PTP_FLAVOR_ALL       , 0x0001, "FixedROM"},
    {USB_PTP_FLAVOR_ALL       , 0x0002, "RemovableROM"},
    {USB_PTP_FLAVOR_ALL       , 0x0003, "FixedRAM"},
    {USB_PTP_FLAVOR_ALL       , 0x0004, "RemovableRAM"},
    {USB_PTP_FLAVOR_NONE      , 0x0000, NULL}
};

/* END SEMI-AUTO Generated Code */
